/**
 * For copyright information see the LICENSE document.
 */

/**
 * Auto-generated by PacketCodeGen, on 2012-09-28
 */

package gwlpr.actions.loginserver.stoc;

import com.realityshard.shardlet.utils.GenericAction;
import java.nio.BufferOverflowException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * This is an automatically generated ShardletAction.
 * It resembles the packet template that has been 
 * parsed from our packet templates xml.
 *
 * Auto generated 
 *
 * @author GWLPR Template Updater
 */
public final class P005_UnknownAction extends GenericAction
{

    private int unknown1;
    private char[] unknown2;
    private char[] unknown3;
    private char[] unknown4;
    private char[] unknown5;
    private char[] unknown6;
    private char[] unknown7;
    private char[] unknown8;


    public short getHeader()
    {
        return 5;
    }


    public void setUnknown1(int newValue)
    {
        unknown1 = newValue;
    }


    public void setUnknown2(char[] newValue)
    {
        unknown2 = newValue;
    }


    public void setUnknown3(char[] newValue)
    {
        unknown3 = newValue;
    }


    public void setUnknown4(char[] newValue)
    {
        unknown4 = newValue;
    }


    public void setUnknown5(char[] newValue)
    {
        unknown5 = newValue;
    }


    public void setUnknown6(char[] newValue)
    {
        unknown6 = newValue;
    }


    public void setUnknown7(char[] newValue)
    {
        unknown7 = newValue;
    }


    public void setUnknown8(char[] newValue)
    {
        unknown8 = newValue;
    }


    private int getSize()
    {
        int size = 20;

        if (unknown2 != null)
        {
            size += 2 * unknown2.length;
        }
        if (unknown3 != null)
        {
            size += 2 * unknown3.length;
        }
        if (unknown4 != null)
        {
            size += 2 * unknown4.length;
        }
        if (unknown5 != null)
        {
            size += 2 * unknown5.length;
        }
        if (unknown6 != null)
        {
            size += 2 * unknown6.length;
        }
        if (unknown7 != null)
        {
            size += 2 * unknown7.length;
        }
        if (unknown8 != null)
        {
            size += 2 * unknown8.length;
        }

        return size;
    }


    @Override
    public boolean serialize()
    {
        int size = getSize();

        if (size == 0)
        {
            return false;
        }

        ByteBuffer buffer = ByteBuffer.allocate(size).order(ByteOrder.LITTLE_ENDIAN);

        try
        {
            buffer.putShort(getHeader());

            buffer.putInt(unknown1);
            short prefix_unknown2;
            if (unknown2 == null)
            {
                prefix_unknown2 = 0;
            }
            else
            {
                prefix_unknown2 = (short) unknown2.length;
            }
            buffer.putShort(prefix_unknown2);
            
            for (int i = 0; i < prefix_unknown2; i++)
            {
                buffer.putChar(unknown2[i]);
            }
            short prefix_unknown3;
            if (unknown3 == null)
            {
                prefix_unknown3 = 0;
            }
            else
            {
                prefix_unknown3 = (short) unknown3.length;
            }
            buffer.putShort(prefix_unknown3);
            
            for (int i = 0; i < prefix_unknown3; i++)
            {
                buffer.putChar(unknown3[i]);
            }
            short prefix_unknown4;
            if (unknown4 == null)
            {
                prefix_unknown4 = 0;
            }
            else
            {
                prefix_unknown4 = (short) unknown4.length;
            }
            buffer.putShort(prefix_unknown4);
            
            for (int i = 0; i < prefix_unknown4; i++)
            {
                buffer.putChar(unknown4[i]);
            }
            short prefix_unknown5;
            if (unknown5 == null)
            {
                prefix_unknown5 = 0;
            }
            else
            {
                prefix_unknown5 = (short) unknown5.length;
            }
            buffer.putShort(prefix_unknown5);
            
            for (int i = 0; i < prefix_unknown5; i++)
            {
                buffer.putChar(unknown5[i]);
            }
            short prefix_unknown6;
            if (unknown6 == null)
            {
                prefix_unknown6 = 0;
            }
            else
            {
                prefix_unknown6 = (short) unknown6.length;
            }
            buffer.putShort(prefix_unknown6);
            
            for (int i = 0; i < prefix_unknown6; i++)
            {
                buffer.putChar(unknown6[i]);
            }
            short prefix_unknown7;
            if (unknown7 == null)
            {
                prefix_unknown7 = 0;
            }
            else
            {
                prefix_unknown7 = (short) unknown7.length;
            }
            buffer.putShort(prefix_unknown7);
            
            for (int i = 0; i < prefix_unknown7; i++)
            {
                buffer.putChar(unknown7[i]);
            }
            short prefix_unknown8;
            if (unknown8 == null)
            {
                prefix_unknown8 = 0;
            }
            else
            {
                prefix_unknown8 = (short) unknown8.length;
            }
            buffer.putShort(prefix_unknown8);
            
            for (int i = 0; i < prefix_unknown8; i++)
            {
                buffer.putChar(unknown8[i]);
            }
        }
        catch (BufferOverflowException e)
        {
            return false;
        }

        setBuffer(buffer);

        return true;
    }
}