/**
 * For copyright information see the LICENSE document.
 */

/**
 * Auto-generated by PacketCodeGen, on 2012-09-28
 */

package gwlpr.actions.loginserver.stoc;

import realityshard.shardlet.utils.GenericAction;
import java.nio.BufferOverflowException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * This is an automatically generated ShardletAction.
 * It resembles the packet template that has been 
 * parsed from our packet templates xml.
 *
 * Auto generated 
 *
 * @author GWLPR Template Updater
 */
public final class P007_UnknownAction extends GenericAction
{

    private int unknown1;
    private byte[] unknown2;
    private int unknown3;
    private char[] unknown4;
    private byte[] unknown5;


    public short getHeader()
    {
        return 7;
    }


    public void setUnknown1(int newValue)
    {
        unknown1 = newValue;
    }


    public void setUnknown2(byte[] newValue)
    {
        unknown2 = newValue;
    }


    public void setUnknown3(int newValue)
    {
        unknown3 = newValue;
    }


    public void setUnknown4(char[] newValue)
    {
        unknown4 = newValue;
    }


    public void setUnknown5(byte[] newValue)
    {
        unknown5 = newValue;
    }


    private int getSize()
    {
        int size = 30;

        if (unknown2 == null)
        {
            return 0;
        }
        
        if (unknown2.length != 16)
        {
            return 0;
        }
        if (unknown4 != null)
        {
            size += 2 * unknown4.length;
        }
        if (unknown5 != null)
        {
            size += 1 * unknown5.length;
        }

        return size;
    }


    @Override
    public boolean serialize()
    {
        int size = getSize();

        if (size == 0)
        {
            return false;
        }

        ByteBuffer buffer = ByteBuffer.allocate(size).order(ByteOrder.LITTLE_ENDIAN);

        try
        {
            buffer.putShort(getHeader());

            buffer.putInt(unknown1);
            for (int i = 0; i < 16; i++)
            {
                buffer.put(unknown2[i]);
            }
            buffer.putInt(unknown3);
            short prefix_unknown4;
            if (unknown4 == null)
            {
                prefix_unknown4 = 0;
            }
            else
            {
                prefix_unknown4 = (short) unknown4.length;
            }
            buffer.putShort(prefix_unknown4);
            
            for (int i = 0; i < prefix_unknown4; i++)
            {
                buffer.putChar(unknown4[i]);
            }
            short prefix_unknown5;
            if (unknown5 == null)
            {
                prefix_unknown5 = 0;
            }
            else
            {
                prefix_unknown5 = (short) unknown5.length;
            }
            buffer.putShort(prefix_unknown5);
            
            for (int i = 0; i < prefix_unknown5; i++)
            {
                buffer.put(unknown5[i]);
            }
        }
        catch (BufferOverflowException e)
        {
            return false;
        }

        setBuffer(buffer);

        return true;
    }
}