
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P004_Unknown
    extends GWAction
{

    public int unknown1;
    public int unknown2;
    public int unknown3;

    static {
        GameServerActionFactory.registerOutbound(P004_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  4;
    }

}
