
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P011_Unknown
    extends GWAction
{

    public String unknown1;

    @Override
    public short getHeader() {
        return  11;
    }

    public void setUnknown1(String unknown1) {
        this.unknown1 = unknown1;
    }

}
