
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.utils.IsArray;
import gwlpr.actions.utils.NestedMarker;
import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P015_Unknown
    extends GenericAction
{

    private int unknown1;
    @IsArray(constant = false, size = 64, prefixLength = 2)
    private P015_Unknown.NestedUnknown2 [] unknown2;

    public short getHeader() {
        return  15;
    }

    public void setUnknown1(int unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(P015_Unknown.NestedUnknown2 [] unknown2) {
        this.unknown2 = unknown2;
    }

    public final class NestedUnknown2
        implements NestedMarker
    {

        private long unknown1;

    }

}
