
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P017_SkillUnlocked
    extends GWAction
{

    public int skillID;
    public short unlocked;

    @Override
    public short getHeader() {
        return  17;
    }

    public void setSkillID(int skillID) {
        this.skillID = skillID;
    }

    public void setUnlocked(short unlocked) {
        this.unlocked = unlocked;
    }

}
