
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.IsArray;
import gwlpr.actions.utils.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P018_Unknown
    extends GWAction
{

    @IsArray(constant = false, size = 128, prefixLength = 2)
    public P018_Unknown.NestedUnknown1 [] unknown1;

    static {
        GameServerActionFactory.registerOutbound(P018_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  18;
    }

    public final static class NestedUnknown1
        implements NestedMarker
    {

        public long unknown1;

    }

}
