
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P021_Unknown
    extends GWAction
{

    public long unknown1;
    public long unknown2;
    public short unknown3;
    public short unknown4;
    public Vector2 unknown5;
    public int unknown6;
    public Vector2 unknown7;
    public short unknown8;
    public float unknown9;
    public float unknown10;
    public long unknown11;
    public long unknown12;
    public long unknown13;
    public long unknown14;
    public long unknown15;
    public long unknown16;
    public long unknown17;
    public Vector2 unknown18;
    public Vector2 unknown19;
    public int unknown20;
    public long unknown21;
    public Vector2 unknown22;
    public int unknown23;

    @Override
    public short getHeader() {
        return  21;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(long unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(short unknown3) {
        this.unknown3 = unknown3;
    }

    public void setUnknown4(short unknown4) {
        this.unknown4 = unknown4;
    }

    public void setUnknown5(Vector2 unknown5) {
        this.unknown5 = unknown5;
    }

    public void setUnknown6(int unknown6) {
        this.unknown6 = unknown6;
    }

    public void setUnknown7(Vector2 unknown7) {
        this.unknown7 = unknown7;
    }

    public void setUnknown8(short unknown8) {
        this.unknown8 = unknown8;
    }

    public void setUnknown9(float unknown9) {
        this.unknown9 = unknown9;
    }

    public void setUnknown10(float unknown10) {
        this.unknown10 = unknown10;
    }

    public void setUnknown11(long unknown11) {
        this.unknown11 = unknown11;
    }

    public void setUnknown12(long unknown12) {
        this.unknown12 = unknown12;
    }

    public void setUnknown13(long unknown13) {
        this.unknown13 = unknown13;
    }

    public void setUnknown14(long unknown14) {
        this.unknown14 = unknown14;
    }

    public void setUnknown15(long unknown15) {
        this.unknown15 = unknown15;
    }

    public void setUnknown16(long unknown16) {
        this.unknown16 = unknown16;
    }

    public void setUnknown17(long unknown17) {
        this.unknown17 = unknown17;
    }

    public void setUnknown18(Vector2 unknown18) {
        this.unknown18 = unknown18;
    }

    public void setUnknown19(Vector2 unknown19) {
        this.unknown19 = unknown19;
    }

    public void setUnknown20(int unknown20) {
        this.unknown20 = unknown20;
    }

    public void setUnknown21(long unknown21) {
        this.unknown21 = unknown21;
    }

    public void setUnknown22(Vector2 unknown22) {
        this.unknown22 = unknown22;
    }

    public void setUnknown23(int unknown23) {
        this.unknown23 = unknown23;
    }

}
