
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P028_MovementSpeed
    extends GWAction
{

    public long agent;
    public float speed;

    static {
        GameServerActionFactory.registerOutbound(P028_MovementSpeed.class);
    }

    @Override
    public short getHeader() {
        return  28;
    }

}
