
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P031_Unknown
    extends GWAction
{

    public long unknown1;
    public Vector2 unknown2;
    public int unknown3;
    public int unknown4;
    public long unknown5;

    static {
        GameServerActionFactory.registerOutbound(P031_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  31;
    }

}
