
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P033_UpdateAgentPosition
    extends GWAction
{

    public long agentID;
    public Vector2 position;
    public int plane;

    static {
        GameServerActionFactory.registerOutbound(P033_UpdateAgentPosition.class);
    }

    @Override
    public short getHeader() {
        return  33;
    }

}
