
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P037_Unknown
    extends GWAction
{

    public String unknown1;
    public long unknown2;
    public long unknown3;
    public long unknown4;
    public long unknown5;
    public long unknown6;
    public long unknown7;

    @Override
    public short getHeader() {
        return  37;
    }

    public void setUnknown1(String unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(long unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(long unknown3) {
        this.unknown3 = unknown3;
    }

    public void setUnknown4(long unknown4) {
        this.unknown4 = unknown4;
    }

    public void setUnknown5(long unknown5) {
        this.unknown5 = unknown5;
    }

    public void setUnknown6(long unknown6) {
        this.unknown6 = unknown6;
    }

    public void setUnknown7(long unknown7) {
        this.unknown7 = unknown7;
    }

}
