
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.IsArray;
import gwlpr.actions.utils.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P047_SetAttributes
    extends GWAction
{

    public long agentID;
    @IsArray(constant = false, size = 48, prefixLength = 2)
    public P047_SetAttributes.NestedData[] data;

    @Override
    public short getHeader() {
        return  47;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setData(P047_SetAttributes.NestedData[] data) {
        this.data = data;
    }

    public final static class NestedData
        implements NestedMarker
    {

        public long unknown1;

        public void setUnknown1(long unknown1) {
            this.unknown1 = unknown1;
        }

    }

}
