
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P050_AgentAllyDestroy
    extends GWAction
{

    public long agent;

    @Override
    public short getHeader() {
        return  50;
    }

    public void setAgent(long agent) {
        this.agent = agent;
    }

}
