
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P050_AgentAllyDestroy
    extends GWAction
{

    public long agent;

    static {
        GameServerActionFactory.registerOutbound(P050_AgentAllyDestroy.class);
    }

    @Override
    public short getHeader() {
        return  50;
    }

}
