
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P052_SkillUpkeepRemove
    extends GWAction
{

    public long caster;
    public long buffID;

    static {
        GameServerActionFactory.registerOutbound(P052_SkillUpkeepRemove.class);
    }

    @Override
    public short getHeader() {
        return  52;
    }

}
