
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P054_SkillEffectTimed
    extends GWAction
{

    public long caster;
    public int skillID;
    public long unknown1;
    public long buffID;
    public long duration;

    static {
        GameServerActionFactory.registerOutbound(P054_SkillEffectTimed.class);
    }

    @Override
    public short getHeader() {
        return  54;
    }

}
