
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P055_Unknown
    extends GWAction
{

    public long agentID1;
    public long unknown2;
    public long unknown3;
    public long unknown4;

    static {
        GameServerActionFactory.registerOutbound(P055_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  55;
    }

}
