
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P056_SkillEffectRemove
    extends GenericAction
{

    private long caster;
    private long buffID;

    public short getHeader() {
        return  56;
    }

    public void setCaster(long caster) {
        this.caster = caster;
    }

    public void setBuffID(long buffID) {
        this.buffID = buffID;
    }

}
