
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P059_Unknown
    extends GWAction
{

    public long unknown1;
    public long unknown2;
    public Vector2 unknown3;
    public int unknown4;

    static {
        GameServerActionFactory.registerOutbound(P059_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  59;
    }

}
