
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P068_QuestAdd
    extends GWAction
{

    public long iD;
    public long status;
    public String category;
    public String name;
    public String givenBy;
    public int mapID;

    @Override
    public short getHeader() {
        return  68;
    }

    public void setID(long iD) {
        this.iD = iD;
    }

    public void setStatus(long status) {
        this.status = status;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setGivenBy(String givenBy) {
        this.givenBy = givenBy;
    }

    public void setMapID(int mapID) {
        this.mapID = mapID;
    }

}
