
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P076_CharacterName
    extends GWAction
{

    public long localID;
    public String name;

    static {
        GameServerActionFactory.registerOutbound(P076_CharacterName.class);
    }

    @Override
    public short getHeader() {
        return  76;
    }

}
