
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P077_Unknown
    extends GenericAction
{

    private long unknown1;
    private long unknown2;
    private long unknown3;
    private short unknown4;
    private long unknown5;
    private long unknown6;
    private String unknown7;

    public short getHeader() {
        return  77;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(long unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(long unknown3) {
        this.unknown3 = unknown3;
    }

    public void setUnknown4(short unknown4) {
        this.unknown4 = unknown4;
    }

    public void setUnknown5(long unknown5) {
        this.unknown5 = unknown5;
    }

    public void setUnknown6(long unknown6) {
        this.unknown6 = unknown6;
    }

    public void setUnknown7(String unknown7) {
        this.unknown7 = unknown7;
    }

}
