
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P088_Unknown
    extends GWAction
{

    public long agentID1;
    public short unknown2;
    public short unknown3;

    static {
        GameServerActionFactory.registerOutbound(P088_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  88;
    }

}
