
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P090_Unknown
    extends GWAction
{

    public long agentID1;
    public Vector2 unknown2;
    public int unknown3;

    @Override
    public short getHeader() {
        return  90;
    }

    public void setAgentID1(long agentID1) {
        this.agentID1 = agentID1;
    }

    public void setUnknown2(Vector2 unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(int unknown3) {
        this.unknown3 = unknown3;
    }

}
