
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P093_Unknown
    extends GWAction
{

    public long agentID1;

    static {
        GameServerActionFactory.registerOutbound(P093_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  93;
    }

}
