
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P094_RequestFile
    extends GenericAction
{

    private long file;

    public short getHeader() {
        return  94;
    }

    public void setFile(long file) {
        this.file = file;
    }

}
