
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P095_PostProcessEffect
    extends GenericAction
{

    private short intensity;
    private long tint;

    public short getHeader() {
        return  95;
    }

    public void setIntensity(short intensity) {
        this.intensity = intensity;
    }

    public void setTint(long tint) {
        this.tint = tint;
    }

}
