
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P099_UpdateAgentEquipment
    extends GenericAction
{

    private long agentID;
    private long slot;
    private long item;

    public short getHeader() {
        return  99;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setSlot(long slot) {
        this.slot = slot;
    }

    public void setItem(long item) {
        this.item = item;
    }

}
