
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P099_UpdateAgentEquipment
    extends GWAction
{

    public long agentID;
    public long slot;
    public long item;

    static {
        GameServerActionFactory.registerOutbound(P099_UpdateAgentEquipment.class);
    }

    @Override
    public short getHeader() {
        return  99;
    }

}
