
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P102_HeroCreate
    extends GenericAction
{

    private int heroID;
    private long agentID;
    private long itemStreamID;
    private long mode;

    public short getHeader() {
        return  102;
    }

    public void setHeroID(int heroID) {
        this.heroID = heroID;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setItemStreamID(long itemStreamID) {
        this.itemStreamID = itemStreamID;
    }

    public void setMode(long mode) {
        this.mode = mode;
    }

}
