
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P102_HeroCreate
    extends GWAction
{

    public int heroID;
    public long agentID;
    public long itemStreamID;
    public long mode;

    static {
        GameServerActionFactory.registerOutbound(P102_HeroCreate.class);
    }

    @Override
    public short getHeader() {
        return  102;
    }

}
