
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.IsArray;
import gwlpr.actions.utils.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P108_Unknown
    extends GWAction
{

    public short unknown1;
    @IsArray(constant = false, size = 32, prefixLength = 2)
    public P108_Unknown.NestedUnknown2 [] unknown2;

    static {
        GameServerActionFactory.registerOutbound(P108_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  108;
    }

    public final static class NestedUnknown2
        implements NestedMarker
    {

        public int unknown1;
        public short unknown2;
        public long unknown3;
        public long unknown4;
        public short unknown5;

    }

}
