
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P109_HeroModel
    extends GenericAction
{

    private int heroID;
    private long modelFile;

    public short getHeader() {
        return  109;
    }

    public void setHeroID(int heroID) {
        this.heroID = heroID;
    }

    public void setModelFile(long modelFile) {
        this.modelFile = modelFile;
    }

}
