
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P114_DialogButton
    extends GWAction
{

    public short icon;
    public String caption;
    public long buttonID;
    public long skillID;

    static {
        GameServerActionFactory.registerOutbound(P114_DialogButton.class);
    }

    @Override
    public short getHeader() {
        return  114;
    }

}
