
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P114_DialogButton
    extends GenericAction
{

    private short icon;
    private String caption;
    private long buttonID;
    private long skillID;

    public short getHeader() {
        return  114;
    }

    public void setIcon(short icon) {
        this.icon = icon;
    }

    public void setCaption(String caption) {
        this.caption = caption;
    }

    public void setButtonID(long buttonID) {
        this.buttonID = buttonID;
    }

    public void setSkillID(long skillID) {
        this.skillID = skillID;
    }

}
