
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P116_DialogBody
    extends GWAction
{

    public String body;

    static {
        GameServerActionFactory.registerOutbound(P116_DialogBody.class);
    }

    @Override
    public short getHeader() {
        return  116;
    }

}
