
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P121_WindowItemsEnd
    extends GWAction
{

    public short windowType;

    static {
        GameServerActionFactory.registerOutbound(P121_WindowItemsEnd.class);
    }

    @Override
    public short getHeader() {
        return  121;
    }

}
