
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.Vector2;
import gwlpr.actions.utils.Vector3;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P125_Unknown
    extends GWAction
{

    public short unknown1;
    public Vector3 unknown2;
    public Vector2 unknown3;

    @Override
    public short getHeader() {
        return  125;
    }

    public void setUnknown1(short unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(Vector3 unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(Vector2 unknown3) {
        this.unknown3 = unknown3;
    }

}
