
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P129_MissionMapIconAdd
    extends GWAction
{

    public long localID;
    public Vector2 position;
    public int plane;
    public short color;
    public long unknown1;
    public long iconHash;
    public String text;

    @Override
    public short getHeader() {
        return  129;
    }

    public void setLocalID(long localID) {
        this.localID = localID;
    }

    public void setPosition(Vector2 position) {
        this.position = position;
    }

    public void setPlane(int plane) {
        this.plane = plane;
    }

    public void setColor(short color) {
        this.color = color;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

    public void setIconHash(long iconHash) {
        this.iconHash = iconHash;
    }

    public void setText(String text) {
        this.text = text;
    }

}
