
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P129_MissionMapIconAdd
    extends GWAction
{

    public long localID;
    public Vector2 position;
    public int plane;
    public short color;
    public long unknown1;
    public long iconHash;
    public String text;

    static {
        GameServerActionFactory.registerOutbound(P129_MissionMapIconAdd.class);
    }

    @Override
    public short getHeader() {
        return  129;
    }

}
