
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.utils.Vector2;
import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P129_MissionMapIconAdd
    extends GenericAction
{

    private long localID;
    private Vector2 position;
    private int plane;
    private short color;
    private long unknown1;
    private long iconHash;
    private String text;

    public short getHeader() {
        return  129;
    }

    public void setLocalID(long localID) {
        this.localID = localID;
    }

    public void setPosition(Vector2 position) {
        this.position = position;
    }

    public void setPlane(int plane) {
        this.plane = plane;
    }

    public void setColor(short color) {
        this.color = color;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

    public void setIconHash(long iconHash) {
        this.iconHash = iconHash;
    }

    public void setText(String text) {
        this.text = text;
    }

}
