
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P130_MissionMapIconRemove
    extends GWAction
{

    public long localID;

    @Override
    public short getHeader() {
        return  130;
    }

    public void setLocalID(long localID) {
        this.localID = localID;
    }

}
