
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P130_MissionMapIconRemove
    extends GenericAction
{

    private long localID;

    public short getHeader() {
        return  130;
    }

    public void setLocalID(long localID) {
        this.localID = localID;
    }

}
