
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.IsArray;
import gwlpr.actions.utils.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P133_Unknown
    extends GWAction
{

    public int unknown1;
    public long unknown2;
    @IsArray(constant = false, size = 16, prefixLength = 2)
    public P133_Unknown.NestedUnknown3 [] unknown3;

    static {
        GameServerActionFactory.registerOutbound(P133_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  133;
    }

    public final static class NestedUnknown3
        implements NestedMarker
    {

        public long unknown1;

    }

}
