
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P138_Unknown
    extends GWAction
{

    public long unknown1;
    public long unknown2;
    public long unknown3;
    public long unknown4;
    public long unknown5;

    static {
        GameServerActionFactory.registerOutbound(P138_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  138;
    }

}
