
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P139_Unknown
    extends GWAction
{

    public short unknown1;
    public String unknown2;

    static {
        GameServerActionFactory.registerOutbound(P139_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  139;
    }

}
