
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P143_UpdateNpcName
    extends GWAction
{

    public long agentID;
    public String name;

    @Override
    public short getHeader() {
        return  143;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setName(String name) {
        this.name = name;
    }

}
