
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P143_UpdateNpcName
    extends GWAction
{

    public long agentID;
    public String name;

    static {
        GameServerActionFactory.registerOutbound(P143_UpdateNpcName.class);
    }

    @Override
    public short getHeader() {
        return  143;
    }

}
