
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P144_UpdateMorale
    extends GenericAction
{

    private long agentID;
    private long morale;

    public short getHeader() {
        return  144;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setMorale(long morale) {
        this.morale = morale;
    }

}
