
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P146_DisplayDialogue
    extends GWAction
{

    public long agentID;
    public String name;
    public short type;
    public String text;

    static {
        GameServerActionFactory.registerOutbound(P146_DisplayDialogue.class);
    }

    @Override
    public short getHeader() {
        return  146;
    }

}
