
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P147_UpdateGenericValue
    extends GWAction
{

    public long valueID;
    public long agentID;
    public long value;

    static {
        GameServerActionFactory.registerOutbound(P147_UpdateGenericValue.class);
    }

    @Override
    public short getHeader() {
        return  147;
    }

}
