
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P149_PlayEffect
    extends GWAction
{

    public Vector2 position;
    public int plane;
    public long agentID;
    public int effectID;
    public short unknown1;
    public short unknown2;

    @Override
    public short getHeader() {
        return  149;
    }

    public void setPosition(Vector2 position) {
        this.position = position;
    }

    public void setPlane(int plane) {
        this.plane = plane;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setEffectID(int effectID) {
        this.effectID = effectID;
    }

    public void setUnknown1(short unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(short unknown2) {
        this.unknown2 = unknown2;
    }

}
