
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.utils.Vector2;
import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P149_PlayEffect
    extends GenericAction
{

    private Vector2 position;
    private int plane;
    private long agentID;
    private int effectID;
    private short unknown1;
    private short unknown2;

    public short getHeader() {
        return  149;
    }

    public void setPosition(Vector2 position) {
        this.position = position;
    }

    public void setPlane(int plane) {
        this.plane = plane;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setEffectID(int effectID) {
        this.effectID = effectID;
    }

    public void setUnknown1(short unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(short unknown2) {
        this.unknown2 = unknown2;
    }

}
