
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P151_UpdateTargetGenericModifier
    extends GenericAction
{

    private long valueID;
    private long target;
    private long caster;
    private long value;

    public short getHeader() {
        return  151;
    }

    public void setValueID(long valueID) {
        this.valueID = valueID;
    }

    public void setTarget(long target) {
        this.target = target;
    }

    public void setCaster(long caster) {
        this.caster = caster;
    }

    public void setValue(long value) {
        this.value = value;
    }

}
