
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P152_Unknown
    extends GWAction
{

    public long agentID1;
    public Vector2 unknown2;
    public int unknown3;
    public long unknown4;
    public long unknown5;
    public long unknown6;
    public short unknown7;

    @Override
    public short getHeader() {
        return  152;
    }

    public void setAgentID1(long agentID1) {
        this.agentID1 = agentID1;
    }

    public void setUnknown2(Vector2 unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(int unknown3) {
        this.unknown3 = unknown3;
    }

    public void setUnknown4(long unknown4) {
        this.unknown4 = unknown4;
    }

    public void setUnknown5(long unknown5) {
        this.unknown5 = unknown5;
    }

    public void setUnknown6(long unknown6) {
        this.unknown6 = unknown6;
    }

    public void setUnknown7(short unknown7) {
        this.unknown7 = unknown7;
    }

}
