
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P153_SpeechBubble
    extends GenericAction
{

    private long agentID;
    private String text;

    public short getHeader() {
        return  153;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setText(String text) {
        this.text = text;
    }

}
