
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P160_AgentSpectate
    extends GWAction
{

    public long agentID;
    public short target;

    static {
        GameServerActionFactory.registerOutbound(P160_AgentSpectate.class);
    }

    @Override
    public short getHeader() {
        return  160;
    }

}
