
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P167_PetDestroy
    extends GWAction
{

    public long pet;

    static {
        GameServerActionFactory.registerOutbound(P167_PetDestroy.class);
    }

    @Override
    public short getHeader() {
        return  167;
    }

}
