
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P170_AvailableProfessions
    extends GenericAction
{

    private long agentID;
    private long professions;

    public short getHeader() {
        return  170;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setProfessions(long professions) {
        this.professions = professions;
    }

}
