
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P171_UpdatePrivProfessions
    extends GWAction
{

    public long agentID;
    public short primaryProf;
    public short secondaryProf;
    public short isPvP;

    @Override
    public short getHeader() {
        return  171;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setPrimaryProf(short primaryProf) {
        this.primaryProf = primaryProf;
    }

    public void setSecondaryProf(short secondaryProf) {
        this.secondaryProf = secondaryProf;
    }

    public void setIsPvP(short isPvP) {
        this.isPvP = isPvP;
    }

}
