
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P173_AddMissionGoal
    extends GWAction
{

    public String goal;
    public long type;

    static {
        GameServerActionFactory.registerOutbound(P173_AddMissionGoal.class);
    }

    @Override
    public short getHeader() {
        return  173;
    }

}
