
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P173_AddMissionGoal
    extends GenericAction
{

    private String goal;
    private long type;

    public short getHeader() {
        return  173;
    }

    public void setGoal(String goal) {
        this.goal = goal;
    }

    public void setType(long type) {
        this.type = type;
    }

}
