
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P200_Unknown
    extends GWAction
{


    static {
        GameServerActionFactory.registerOutbound(P200_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  200;
    }

}
