
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.IsArray;
import gwlpr.actions.utils.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P206_UpdateSkillBar
    extends GWAction
{

    public long agentID;
    @IsArray(constant = false, size = 8, prefixLength = 2)
    public P206_UpdateSkillBar.NestedSkillBar[] skillBar;
    @IsArray(constant = false, size = 8, prefixLength = 2)
    public P206_UpdateSkillBar.NestedSkillBarPvPMask[] skillBarPvPMask;
    public short unknown1;

    @Override
    public short getHeader() {
        return  206;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setSkillBar(P206_UpdateSkillBar.NestedSkillBar[] skillBar) {
        this.skillBar = skillBar;
    }

    public void setSkillBarPvPMask(P206_UpdateSkillBar.NestedSkillBarPvPMask[] skillBarPvPMask) {
        this.skillBarPvPMask = skillBarPvPMask;
    }

    public void setUnknown1(short unknown1) {
        this.unknown1 = unknown1;
    }

    public final static class NestedSkillBar
        implements NestedMarker
    {

        public long unknown1;

        public void setUnknown1(long unknown1) {
            this.unknown1 = unknown1;
        }

    }

    public final static class NestedSkillBarPvPMask
        implements NestedMarker
    {

        public long unknown1;

        public void setUnknown1(long unknown1) {
            this.unknown1 = unknown1;
        }

    }

}
