
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P217_SkillRecharge
    extends GWAction
{

    public long agentID;
    public int skillID;
    public long skillInstance;
    public long recharge;

    static {
        GameServerActionFactory.registerOutbound(P217_SkillRecharge.class);
    }

    @Override
    public short getHeader() {
        return  217;
    }

}
