
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P221_UpdateFaction
    extends GWAction
{

    public long experience;
    public long kurzickFree;
    public long kurzickTotal;
    public long luxonFree;
    public long luxonTotal;
    public long imperialFree;
    public long imperialTotal;
    public long unknown1;
    public long unknown2;
    public long level;
    public long morale;
    public long balthFree;
    public long balthTotal;
    public long skillFree;
    public long skillTotal;

    static {
        GameServerActionFactory.registerOutbound(P221_UpdateFaction.class);
    }

    @Override
    public short getHeader() {
        return  221;
    }

}
