
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P223_UpdateMaxLuxonFaction
    extends GWAction
{

    public long maxFaction;

    @Override
    public short getHeader() {
        return  223;
    }

    public void setMaxFaction(long maxFaction) {
        this.maxFaction = maxFaction;
    }

}
