
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P223_UpdateMaxLuxonFaction
    extends GWAction
{

    public long maxFaction;

    static {
        GameServerActionFactory.registerOutbound(P223_UpdateMaxLuxonFaction.class);
    }

    @Override
    public short getHeader() {
        return  223;
    }

}
