
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P224_UpdateMaxBalthFaction
    extends GenericAction
{

    private long maxFaction;

    public short getHeader() {
        return  224;
    }

    public void setMaxFaction(long maxFaction) {
        this.maxFaction = maxFaction;
    }

}
