
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P226_ModifyFaction
    extends GWAction
{

    public long type;
    public long amount;

    static {
        GameServerActionFactory.registerOutbound(P226_ModifyFaction.class);
    }

    @Override
    public short getHeader() {
        return  226;
    }

}
