
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P232_TitleRankDisplay
    extends GWAction
{

    public int characterLocalID;
    public long rankID;

    static {
        GameServerActionFactory.registerOutbound(P232_TitleRankDisplay.class);
    }

    @Override
    public short getHeader() {
        return  232;
    }

}
