
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P239_VanquishReward
    extends GWAction
{

    public int mapID;
    public long experienceEarned;
    public long goldEarned;

    static {
        GameServerActionFactory.registerOutbound(P239_VanquishReward.class);
    }

    @Override
    public short getHeader() {
        return  239;
    }

}
