
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P240_VanquishProgress
    extends GenericAction
{

    private long foesVanquished;
    private long foesRemaining;

    public short getHeader() {
        return  240;
    }

    public void setFoesVanquished(long foesVanquished) {
        this.foesVanquished = foesVanquished;
    }

    public void setFoesRemaining(long foesRemaining) {
        this.foesRemaining = foesRemaining;
    }

}
