
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P240_VanquishProgress
    extends GWAction
{

    public long foesVanquished;
    public long foesRemaining;

    static {
        GameServerActionFactory.registerOutbound(P240_VanquishProgress.class);
    }

    @Override
    public short getHeader() {
        return  240;
    }

}
