
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P241_ReportPlayer
    extends GWAction
{

    public String characterName;
    public short isPvP;

    static {
        GameServerActionFactory.registerOutbound(P241_ReportPlayer.class);
    }

    @Override
    public short getHeader() {
        return  241;
    }

}
