
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P242_Unknown
    extends GenericAction
{


    public short getHeader() {
        return  242;
    }

}
