
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P257_ObjectDialogBody
    extends GWAction
{

    public String body;

    static {
        GameServerActionFactory.registerOutbound(P257_ObjectDialogBody.class);
    }

    @Override
    public short getHeader() {
        return  257;
    }

}
