
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P258_ObjectDialogSender
    extends GenericAction
{

    private long agentID;

    public short getHeader() {
        return  258;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

}
