
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P260_ManipulateMapObject
    extends GenericAction
{

    private int objectID;
    private short action;
    private long frequency;

    public short getHeader() {
        return  260;
    }

    public void setObjectID(int objectID) {
        this.objectID = objectID;
    }

    public void setAction(short action) {
        this.action = action;
    }

    public void setFrequency(long frequency) {
        this.frequency = frequency;
    }

}
