
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.IsArray;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P269_GuildAllyRemove
    extends GWAction
{

    @IsArray(constant = true, size = 16, prefixLength = -1)
    public byte[] guildHallData;

    @Override
    public short getHeader() {
        return  269;
    }

    public void setGuildHallData(byte[] guildHallData) {
        this.guildHallData = guildHallData;
    }

}
