
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P273_FactionLine
    extends GenericAction
{

    private long unknown1;
    private short position;

    public short getHeader() {
        return  273;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

    public void setPosition(short position) {
        this.position = position;
    }

}
