
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P274_GuildStreamEnd
    extends GWAction
{


    static {
        GameServerActionFactory.registerOutbound(P274_GuildStreamEnd.class);
    }

    @Override
    public short getHeader() {
        return  274;
    }

}
