
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P276_GuildQualifierPoints
    extends GWAction
{

    public int localID;
    public long amount;

    @Override
    public short getHeader() {
        return  276;
    }

    public void setLocalID(int localID) {
        this.localID = localID;
    }

    public void setAmount(long amount) {
        this.amount = amount;
    }

}
