
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P280_GuildFaction
    extends GWAction
{

    public int localID;
    public short allegiance;
    public long amount;

    static {
        GameServerActionFactory.registerOutbound(P280_GuildFaction.class);
    }

    @Override
    public short getHeader() {
        return  280;
    }

}
