
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P280_GuildFaction
    extends GenericAction
{

    private int localID;
    private short allegiance;
    private long amount;

    public short getHeader() {
        return  280;
    }

    public void setLocalID(int localID) {
        this.localID = localID;
    }

    public void setAllegiance(short allegiance) {
        this.allegiance = allegiance;
    }

    public void setAmount(long amount) {
        this.amount = amount;
    }

}
