
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.IsArray;


/**
 * Auto-generated by PacketCodeGen.
 * This can be used to display a guild invite,
 * alliance invite, or guild guest in the guild
 * window.
 * 
 */
public final class P281_GuildInvite
    extends GWAction
{

    @IsArray(constant = true, size = 16, prefixLength = -1)
    public byte[] guildHallData;
    public String guildName;
    public String guildTag;
    public String invitedBy;
    public long date;
    public long minutes;
    public short type;

    static {
        GameServerActionFactory.registerOutbound(P281_GuildInvite.class);
    }

    @Override
    public short getHeader() {
        return  281;
    }

}
