
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P283_GuildRank
    extends GWAction
{

    public int localID;
    public long rank;

    static {
        GameServerActionFactory.registerOutbound(P283_GuildRank.class);
    }

    @Override
    public short getHeader() {
        return  283;
    }

}
