
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P284_GuildFeatures
    extends GWAction
{

    public int localID;
    public short features;

    @Override
    public short getHeader() {
        return  284;
    }

    public void setLocalID(int localID) {
        this.localID = localID;
    }

    public void setFeatures(short features) {
        this.features = features;
    }

}
