
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P284_GuildFeatures
    extends GenericAction
{

    private int localID;
    private short features;

    public short getHeader() {
        return  284;
    }

    public void setLocalID(int localID) {
        this.localID = localID;
    }

    public void setFeatures(short features) {
        this.features = features;
    }

}
