
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * This is used to display players in the guild
 * window. After a guild player has been created, you
 * can send the packet again with the same primary
 * name to update their info. (e.g set them offline)
 * 
 */
public final class P285_GuildPlayer
    extends GenericAction
{

    private String primaryName;
    private String displayName;
    private String invitedBy;
    private String contextInfo;
    private long unknown1;
    private long lastLoggedOn;
    private long joinDate;
    private long status;
    private short memberType;

    public short getHeader() {
        return  285;
    }

    public void setPrimaryName(String primaryName) {
        this.primaryName = primaryName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public void setInvitedBy(String invitedBy) {
        this.invitedBy = invitedBy;
    }

    public void setContextInfo(String contextInfo) {
        this.contextInfo = contextInfo;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

    public void setLastLoggedOn(long lastLoggedOn) {
        this.lastLoggedOn = lastLoggedOn;
    }

    public void setJoinDate(long joinDate) {
        this.joinDate = joinDate;
    }

    public void setStatus(long status) {
        this.status = status;
    }

    public void setMemberType(short memberType) {
        this.memberType = memberType;
    }

}
