
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * This is used to display players in the guild
 * window. After a guild player has been created, you
 * can send the packet again with the same primary
 * name to update their info. (e.g set them offline)
 * 
 */
public final class P285_GuildPlayer
    extends GWAction
{

    public String primaryName;
    public String displayName;
    public String invitedBy;
    public String contextInfo;
    public long unknown1;
    public long lastLoggedOn;
    public long joinDate;
    public long status;
    public short memberType;

    static {
        GameServerActionFactory.registerOutbound(P285_GuildPlayer.class);
    }

    @Override
    public short getHeader() {
        return  285;
    }

}
