
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P294_GuildRating
    extends GenericAction
{

    private int localID;
    private long rating;

    public short getHeader() {
        return  294;
    }

    public void setLocalID(int localID) {
        this.localID = localID;
    }

    public void setRating(long rating) {
        this.rating = rating;
    }

}
