
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P294_GuildRating
    extends GWAction
{

    public int localID;
    public long rating;

    @Override
    public short getHeader() {
        return  294;
    }

    public void setLocalID(int localID) {
        this.localID = localID;
    }

    public void setRating(long rating) {
        this.rating = rating;
    }

}
