
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P303_ItemQuantity
    extends GWAction
{

    public long itemLocalID;
    public long quantity;

    static {
        GameServerActionFactory.registerOutbound(P303_ItemQuantity.class);
    }

    @Override
    public short getHeader() {
        return  303;
    }

}
