
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P304_ItemOwner
    extends GenericAction
{

    private long itemLocalID;
    private String name;

    public short getHeader() {
        return  304;
    }

    public void setItemLocalID(long itemLocalID) {
        this.itemLocalID = itemLocalID;
    }

    public void setName(String name) {
        this.name = name;
    }

}
