
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P308_ItemLocation
    extends GenericAction
{

    private int itemStreamID;
    private long itemLocalID;
    private int pageID;
    private short slot;

    public short getHeader() {
        return  308;
    }

    public void setItemStreamID(int itemStreamID) {
        this.itemStreamID = itemStreamID;
    }

    public void setItemLocalID(long itemLocalID) {
        this.itemLocalID = itemLocalID;
    }

    public void setPageID(int pageID) {
        this.pageID = pageID;
    }

    public void setSlot(short slot) {
        this.slot = slot;
    }

}
