
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P308_ItemLocation
    extends GWAction
{

    public int itemStreamID;
    public long itemLocalID;
    public int pageID;
    public short slot;

    @Override
    public short getHeader() {
        return  308;
    }

    public void setItemStreamID(int itemStreamID) {
        this.itemStreamID = itemStreamID;
    }

    public void setItemLocalID(long itemLocalID) {
        this.itemLocalID = itemLocalID;
    }

    public void setPageID(int pageID) {
        this.pageID = pageID;
    }

    public void setSlot(short slot) {
        this.slot = slot;
    }

}
