
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P314_ItemStreamCreate
    extends GWAction
{

    public int streamID;
    public short isHero;

    @Override
    public short getHeader() {
        return  314;
    }

    public void setStreamID(int streamID) {
        this.streamID = streamID;
    }

    public void setIsHero(short isHero) {
        this.isHero = isHero;
    }

}
