
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P314_ItemStreamCreate
    extends GWAction
{

    public int streamID;
    public short isHero;

    static {
        GameServerActionFactory.registerOutbound(P314_ItemStreamCreate.class);
    }

    @Override
    public short getHeader() {
        return  314;
    }

}
