
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P318_UpdateActiveWeaponset
    extends GenericAction
{

    private int streamID;
    private short slot;

    public short getHeader() {
        return  318;
    }

    public void setStreamID(int streamID) {
        this.streamID = streamID;
    }

    public void setSlot(short slot) {
        this.slot = slot;
    }

}
