
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P319_ItemPageSlots
    extends GWAction
{

    public int itemStreamID;
    public int pageID;
    public short slots;

    @Override
    public short getHeader() {
        return  319;
    }

    public void setItemStreamID(int itemStreamID) {
        this.itemStreamID = itemStreamID;
    }

    public void setPageID(int pageID) {
        this.pageID = pageID;
    }

    public void setSlots(short slots) {
        this.slots = slots;
    }

}
