
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P322_Unknown
    extends GWAction
{

    public int unknown1;
    public short unknown2;
    public short unknown3;

    static {
        GameServerActionFactory.registerOutbound(P322_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  322;
    }

}
