
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P329_MoveBagIntoStorage
    extends GWAction
{

    public int itemStreamID;
    public long bagLocalID;
    public int pageID;
    public short slot;

    static {
        GameServerActionFactory.registerOutbound(P329_MoveBagIntoStorage.class);
    }

    @Override
    public short getHeader() {
        return  329;
    }

}
