
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P336_ItemProfession
    extends GenericAction
{

    private long itemLocalID;
    private short profession;

    public short getHeader() {
        return  336;
    }

    public void setItemLocalID(long itemLocalID) {
        this.itemLocalID = itemLocalID;
    }

    public void setProfession(short profession) {
        this.profession = profession;
    }

}
