
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.IsArray;
import gwlpr.actions.utils.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P338_Unknown
    extends GWAction
{

    public int unknown1;
    @IsArray(constant = false, size = 7, prefixLength = 2)
    public P338_Unknown.NestedUnknown2 [] unknown2;

    static {
        GameServerActionFactory.registerOutbound(P338_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  338;
    }

    public final static class NestedUnknown2
        implements NestedMarker
    {

        public short unknown1;
        public int unknown2;
        public short unknown3;
        public int unknown4;
        public int unknown5;
        public int unknown6;
        public int unknown7;

    }

}
