
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.IsArray;
import gwlpr.actions.utils.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P338_Unknown
    extends GWAction
{

    public int unknown1;
    @IsArray(constant = false, size = 7, prefixLength = 2)
    public P338_Unknown.NestedUnknown2 [] unknown2;

    @Override
    public short getHeader() {
        return  338;
    }

    public void setUnknown1(int unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(P338_Unknown.NestedUnknown2 [] unknown2) {
        this.unknown2 = unknown2;
    }

    public final static class NestedUnknown2
        implements NestedMarker
    {

        public short unknown1;
        public int unknown2;
        public short unknown3;
        public int unknown4;
        public int unknown5;
        public int unknown6;
        public int unknown7;

        public void setUnknown1(short unknown1) {
            this.unknown1 = unknown1;
        }

        public void setUnknown2(int unknown2) {
            this.unknown2 = unknown2;
        }

        public void setUnknown3(short unknown3) {
            this.unknown3 = unknown3;
        }

        public void setUnknown4(int unknown4) {
            this.unknown4 = unknown4;
        }

        public void setUnknown5(int unknown5) {
            this.unknown5 = unknown5;
        }

        public void setUnknown6(int unknown6) {
            this.unknown6 = unknown6;
        }

        public void setUnknown7(int unknown7) {
            this.unknown7 = unknown7;
        }

    }

}
