
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P360_Unknown
    extends GenericAction
{

    private long unknown1;

    public short getHeader() {
        return  360;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

}
