
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P362_Unknown
    extends GWAction
{

    public long unknown1;
    public short unknown2;
    public long unknown3;
    public long unknown4;
    public long unknown5;
    public long unknown6;
    public long unknown7;
    public long unknown8;
    public short unknown9;
    public short unknown10;
    public short unknown11;
    public short unknown12;
    public short unknown13;
    public int unknown14;
    public int unknown15;
    public int unknown16;
    public int unknown17;
    public int unknown18;
    public long unknown19;
    public short unknown20;
    public short unknown21;
    public long unknown22;
    public short unknown23;

    static {
        GameServerActionFactory.registerOutbound(P362_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  362;
    }

}
