
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P364_Unknown
    extends GWAction
{

    public long unknown1;
    public int unknown2;

    static {
        GameServerActionFactory.registerOutbound(P364_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  364;
    }

}
