
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P374_Unknown
    extends GWAction
{

    public String unknown1;
    public short unknown2;
    public long unknown3;
    public long unknown4;

    @Override
    public short getHeader() {
        return  374;
    }

    public void setUnknown1(String unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(short unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(long unknown3) {
        this.unknown3 = unknown3;
    }

    public void setUnknown4(long unknown4) {
        this.unknown4 = unknown4;
    }

}
