
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P376_Unknown
    extends GWAction
{

    public String unknown1;
    public short unknown2;

    static {
        GameServerActionFactory.registerOutbound(P376_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  376;
    }

}
