
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P377_Unknown
    extends GWAction
{

    public long unknown1;

    @Override
    public short getHeader() {
        return  377;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

}
