
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P380_CharacterCreateAcknowledge
    extends GenericAction
{


    public short getHeader() {
        return  380;
    }

}
