
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P389_ChallengeRecordsDisplay
    extends GWAction
{

    public int mission;
    public short type;

    @Override
    public short getHeader() {
        return  389;
    }

    public void setMission(int mission) {
        this.mission = mission;
    }

    public void setType(short type) {
        this.type = type;
    }

}
