
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P391_InstanceLoadSpawnPoint
    extends GWAction
{

    public long mapFile;
    public Vector2 position;
    public int plane;
    public short unknown1;
    public short isCinematic;

    static {
        GameServerActionFactory.registerOutbound(P391_InstanceLoadSpawnPoint.class);
    }

    @Override
    public short getHeader() {
        return  391;
    }

}
