
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P397_Unknown
    extends GenericAction
{

    private String unknown1;

    public short getHeader() {
        return  397;
    }

    public void setUnknown1(String unknown1) {
        this.unknown1 = unknown1;
    }

}
