
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.IsArray;
import gwlpr.actions.utils.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P400_Unknown
    extends GWAction
{

    @IsArray(constant = false, size = 16, prefixLength = 2)
    public P400_Unknown.NestedUnknown1 [] unknown1;

    @Override
    public short getHeader() {
        return  400;
    }

    public void setUnknown1(P400_Unknown.NestedUnknown1 [] unknown1) {
        this.unknown1 = unknown1;
    }

    public final static class NestedUnknown1
        implements NestedMarker
    {

        public int unknown1;
        public long unknown2;

        public void setUnknown1(int unknown1) {
            this.unknown1 = unknown1;
        }

        public void setUnknown2(long unknown2) {
            this.unknown2 = unknown2;
        }

    }

}
