
package gwlpr.actions.gameserver.outbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P407_Unknown
    extends GenericAction
{

    private short unknown1;
    private short unknown2;
    private long unknown3;
    private String unknown4;
    private long unknown5;
    private String unknown6;
    private long unknown7;
    private short unknown8;
    private short unknown9;

    public short getHeader() {
        return  407;
    }

    public void setUnknown1(short unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(short unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(long unknown3) {
        this.unknown3 = unknown3;
    }

    public void setUnknown4(String unknown4) {
        this.unknown4 = unknown4;
    }

    public void setUnknown5(long unknown5) {
        this.unknown5 = unknown5;
    }

    public void setUnknown6(String unknown6) {
        this.unknown6 = unknown6;
    }

    public void setUnknown7(long unknown7) {
        this.unknown7 = unknown7;
    }

    public void setUnknown8(short unknown8) {
        this.unknown8 = unknown8;
    }

    public void setUnknown9(short unknown9) {
        this.unknown9 = unknown9;
    }

}
