
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P419_PartyDisplay
    extends GWAction
{

    public int partyId;
    public short isInviteEnabled;

    static {
        GameServerActionFactory.registerOutbound(P419_PartyDisplay.class);
    }

    @Override
    public short getHeader() {
        return  419;
    }

}
