
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P423_Unknown
    extends GWAction
{


    @Override
    public short getHeader() {
        return  423;
    }

}
