
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P435_PartyAddHero
    extends GWAction
{

    public int partyId;
    public int charLocalID;
    public int agentID;
    public short heroID;
    public short level;

    static {
        GameServerActionFactory.registerOutbound(P435_PartyAddHero.class);
    }

    @Override
    public short getHeader() {
        return  435;
    }

}
