
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P436_PartyRemoveHero
    extends GWAction
{

    public int partyId;
    public int charLocalID;
    public int agentID;

    static {
        GameServerActionFactory.registerOutbound(P436_PartyRemoveHero.class);
    }

    @Override
    public short getHeader() {
        return  436;
    }

}
