
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P441_Unknown
    extends GWAction
{

    public int unknown1;

    static {
        GameServerActionFactory.registerOutbound(P441_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  441;
    }

}
