
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P444_PartyMemberAdd
    extends GWAction
{

    public int partyId;
    public int charLocalID;
    public short isLoaded;

    @Override
    public short getHeader() {
        return  444;
    }

    public void setPartyId(int partyId) {
        this.partyId = partyId;
    }

    public void setCharLocalID(int charLocalID) {
        this.charLocalID = charLocalID;
    }

    public void setIsLoaded(short isLoaded) {
        this.isLoaded = isLoaded;
    }

}
