
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P444_PartyMemberAdd
    extends GWAction
{

    public int partyId;
    public int charLocalID;
    public short isLoaded;

    static {
        GameServerActionFactory.registerOutbound(P444_PartyMemberAdd.class);
    }

    @Override
    public short getHeader() {
        return  444;
    }

}
