
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P450_PartyMemberReady
    extends GWAction
{

    public int partyId;
    public int charLocalID;
    public short isReady;

    static {
        GameServerActionFactory.registerOutbound(P450_PartyMemberReady.class);
    }

    @Override
    public short getHeader() {
        return  450;
    }

}
