
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P452_PartyMembersEnd
    extends GWAction
{

    public int partyId;

    @Override
    public short getHeader() {
        return  452;
    }

    public void setPartyId(int partyId) {
        this.partyId = partyId;
    }

}
