
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.IsArray;
import gwlpr.actions.utils.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P456_Unknown
    extends GWAction
{

    @IsArray(constant = false, size = 16, prefixLength = 2)
    public P456_Unknown.NestedUnknown1 [] unknown1;
    @IsArray(constant = false, size = 16, prefixLength = 2)
    public P456_Unknown.NestedUnknown2 [] unknown2;

    @Override
    public short getHeader() {
        return  456;
    }

    public void setUnknown1(P456_Unknown.NestedUnknown1 [] unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(P456_Unknown.NestedUnknown2 [] unknown2) {
        this.unknown2 = unknown2;
    }

    public final static class NestedUnknown1
        implements NestedMarker
    {

        public int unknown1;

        public void setUnknown1(int unknown1) {
            this.unknown1 = unknown1;
        }

    }

    public final static class NestedUnknown2
        implements NestedMarker
    {

        public long unknown1;
        public long unknown2;
        public long unknown3;

        public void setUnknown1(long unknown1) {
            this.unknown1 = unknown1;
        }

        public void setUnknown2(long unknown2) {
            this.unknown2 = unknown2;
        }

        public void setUnknown3(long unknown3) {
            this.unknown3 = unknown3;
        }

    }

}
