
package gwlpr.actions.gameserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P478_Unknown
    extends GWAction
{


    @Override
    public short getHeader() {
        return  478;
    }

}
