/**
 * For copyright information see the LICENSE document.
 */

/**
 * Auto-generated by PacketCodeGen, on 2012-09-28
 */

package gwlpr.actions.gameserver.stoc;

import realityshard.shardlet.utils.GenericAction;
import java.nio.BufferOverflowException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * This is an automatically generated ShardletAction.
 * It resembles the packet template that has been 
 * parsed from our packet templates xml.
 *
 *
 * @author GWLPR Template Updater
 */
public final class P012_HeroUnlockedAction extends GenericAction
{

    private byte heroID;
    private byte profession;
    private int nPCFile;
    private int modelFile;
    private byte data5;


    public short getHeader()
    {
        return 12;
    }


    public void setHeroID(byte newValue)
    {
        heroID = newValue;
    }


    public void setProfession(byte newValue)
    {
        profession = newValue;
    }


    public void setNPCFile(int newValue)
    {
        nPCFile = newValue;
    }


    public void setModelFile(int newValue)
    {
        modelFile = newValue;
    }


    public void setData5(byte newValue)
    {
        data5 = newValue;
    }


    private int getSize()
    {
        return 13;
    }


    @Override
    public boolean serialize()
    {
        int size = getSize();

        if (size == 0)
        {
            return false;
        }

        ByteBuffer buffer = ByteBuffer.allocate(size).order(ByteOrder.LITTLE_ENDIAN);

        try
        {
            buffer.putShort(getHeader());

            buffer.put(heroID);
            buffer.put(profession);
            buffer.putInt(nPCFile);
            buffer.putInt(modelFile);
            buffer.put(data5);
        }
        catch (BufferOverflowException e)
        {
            return false;
        }

        setBuffer(buffer);

        return true;
    }
}