/**
 * For copyright information see the LICENSE document.
 */

/**
 * Auto-generated by PacketCodeGen, on 2012-09-28
 */

package gwlpr.actions.gameserver.stoc;

import realityshard.shardlet.utils.GenericAction;
import java.nio.BufferOverflowException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * This is an automatically generated ShardletAction.
 * It resembles the packet template that has been 
 * parsed from our packet templates xml.
 *
 *
 * @author GWLPR Template Updater
 */
public final class P051_SkillUpkeepAddAction extends GenericAction
{

    private int caster;
    private int target;
    private short skillID;
    private int data2;
    private int buffID;


    public short getHeader()
    {
        return 51;
    }


    public void setCaster(int newValue)
    {
        caster = newValue;
    }


    public void setTarget(int newValue)
    {
        target = newValue;
    }


    public void setSkillID(short newValue)
    {
        skillID = newValue;
    }


    public void setData2(int newValue)
    {
        data2 = newValue;
    }


    public void setBuffID(int newValue)
    {
        buffID = newValue;
    }


    private int getSize()
    {
        return 20;
    }


    @Override
    public boolean serialize()
    {
        int size = getSize();

        if (size == 0)
        {
            return false;
        }

        ByteBuffer buffer = ByteBuffer.allocate(size).order(ByteOrder.LITTLE_ENDIAN);

        try
        {
            buffer.putShort(getHeader());

            buffer.putInt(caster);
            buffer.putInt(target);
            buffer.putShort(skillID);
            buffer.putInt(data2);
            buffer.putInt(buffID);
        }
        catch (BufferOverflowException e)
        {
            return false;
        }

        setBuffer(buffer);

        return true;
    }
}