/**
 * For copyright information see the LICENSE document.
 */

/**
 * Auto-generated by PacketCodeGen, on 2012-09-28
 */

package gwlpr.actions.gameserver.stoc;

import com.realityshard.shardlet.utils.GenericAction;
import java.nio.BufferOverflowException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * This is an automatically generated ShardletAction.
 * It resembles the packet template that has been 
 * parsed from our packet templates xml.
 *
 *
 * @author GWLPR Template Updater
 */
public final class P205_UpdateSkillAction extends GenericAction
{

    private int agentID;
    private byte slot;
    private short skillID;
    private int skillInstance;


    public short getHeader()
    {
        return 205;
    }


    public void setAgentID(int newValue)
    {
        agentID = newValue;
    }


    public void setSlot(byte newValue)
    {
        slot = newValue;
    }


    public void setSkillID(short newValue)
    {
        skillID = newValue;
    }


    public void setSkillInstance(int newValue)
    {
        skillInstance = newValue;
    }


    private int getSize()
    {
        return 13;
    }


    @Override
    public boolean serialize()
    {
        int size = getSize();

        if (size == 0)
        {
            return false;
        }

        ByteBuffer buffer = ByteBuffer.allocate(size).order(ByteOrder.LITTLE_ENDIAN);

        try
        {
            buffer.putShort(getHeader());

            buffer.putInt(agentID);
            buffer.put(slot);
            buffer.putShort(skillID);
            buffer.putInt(skillInstance);
        }
        catch (BufferOverflowException e)
        {
            return false;
        }

        setBuffer(buffer);

        return true;
    }
}