/**
 * For copyright information see the LICENSE document.
 */

/**
 * Auto-generated by PacketCodeGen, on 2012-09-28
 */

package com.gamerevision.gwlpr.actions.loginserver.ctos;

import com.realityshard.shardlet.EventAggregator;
import com.realityshard.shardlet.utils.GenericTriggerableAction;
import java.nio.BufferUnderflowException;
import java.nio.ByteBuffer;

/**
 * This is an automatically generated ShardletAction.
 * It resembles the packet template that has been 
 * parsed from our packet templates xml.
 *
 *
 * @author GWLPR Template Updater
 */
public final class P041_CharacterPlayInfoAction extends GenericTriggerableAction
{

    private int loginCount;
    private int data1;
    private int gameMapId;
    private int data2;
    private int data3;
    private int data4;


    public short getHeader()
    {
        return 41;
    }


    public int getLoginCount()
    {
        return loginCount;
    }


    public int getData1()
    {
        return data1;
    }


    public int getGameMapId()
    {
        return gameMapId;
    }


    public int getData2()
    {
        return data2;
    }


    public int getData3()
    {
        return data3;
    }


    public int getData4()
    {
        return data4;
    }


    @Override
    public boolean deserialize()
    {
        ByteBuffer buffer = getBuffer();
        int bufferPosition = buffer.position();

        try
        {
            loginCount = buffer.getInt();
            data1 = buffer.getInt();
            gameMapId = buffer.getInt();
            data2 = buffer.getInt();
            data3 = buffer.getInt();
            data4 = buffer.getInt();
        }
        catch (BufferUnderflowException e)
        {
            buffer.position(bufferPosition);
            return false;
        }

        return true;
    }


    @Override
    public void triggerEvent(EventAggregator aggregator)
    {
        aggregator.triggerEvent(this);
    }
}