/**
 * For copyright information see the LICENSE document.
 */

/**
 * Auto-generated by PacketCodeGen, on 2012-05-28
 */

package com.gamerevision.gwlpr.actions.loginserver.ctos;

import com.realityshard.shardlet.EventAggregator;
import com.realityshard.shardlet.utils.GenericTriggerableAction;
import java.nio.BufferUnderflowException;
import java.nio.ByteBuffer;

/**
 * This is an unencrypted packet.
 * Its the second packet to be sent by the client.
 */
public final class P16896_ClientSeedAction extends GenericTriggerableAction
{

    private byte[] clientSeed;

    
    public short getHeader()
    {
        return 16896;
    }


    public byte[] getClientSeed()
    {
        return clientSeed;
    }


    @Override
    public boolean deserialize()
    {
        ByteBuffer buffer = getBuffer();
        int bufferPosition = buffer.position();

        try
        {
            clientSeed = new byte[64];
            
            for (int i = 0; i < 64; i++)
            {
                clientSeed[i] = buffer.get();
            }
        }
        catch (BufferUnderflowException e)
        {
            buffer.position(bufferPosition);
            return false;
        }

        return true;
    }


    @Override
    public void triggerEvent(EventAggregator aggregator)
    {
        aggregator.triggerEvent(this);
    }
}