
package gwlpr.actions.loginserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.loginserver.LoginServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P002_Unknown
    extends GWAction
{

    public long unknown1;
    public long unknown2;

    static {
        LoginServerActionFactory.registerOutbound(P002_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  2;
    }

}
