
package gwlpr.actions.loginserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.IsArray;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P007_Unknown
    extends GWAction
{

    public long unknown1;
    @IsArray(constant = true, size = 16, prefixLength = -1)
    public byte[] unknown2;
    public long unknown3;
    public String unknown4;
    @IsArray(constant = false, size = 64, prefixLength = 2)
    public byte[] unknown5;

    @Override
    public short getHeader() {
        return  7;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(byte[] unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(long unknown3) {
        this.unknown3 = unknown3;
    }

    public void setUnknown4(String unknown4) {
        this.unknown4 = unknown4;
    }

    public void setUnknown5(byte[] unknown5) {
        this.unknown5 = unknown5;
    }

}
