
package gwlpr.actions.loginserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.IsArray;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P008_Unknown
    extends GWAction
{

    public long unknown1;
    public long unknown2;
    @IsArray(constant = true, size = 24, prefixLength = -1)
    public byte[] unknown3;
    public long unknown4;

    @Override
    public short getHeader() {
        return  8;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(long unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(byte[] unknown3) {
        this.unknown3 = unknown3;
    }

    public void setUnknown4(long unknown4) {
        this.unknown4 = unknown4;
    }

}
