
package gwlpr.actions.loginserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P020_FriendsListEnd
    extends GWAction
{

    public long loginCount;
    public long unknown1;

    @Override
    public short getHeader() {
        return  20;
    }

    public void setLoginCount(long loginCount) {
        this.loginCount = loginCount;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

}
