
package gwlpr.actions.loginserver.outbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P025_Unknown
    extends GWAction
{


    @Override
    public short getHeader() {
        return  25;
    }

}
