
package gwlpr.actions.loginserver.outbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.loginserver.LoginServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P030_Unknown
    extends GWAction
{

    public long unknown1;
    public long unknown2;
    public long unknown3;
    public long unknown4;
    public long unknown5;
    public long unknown6;
    public long unknown7;
    public long unknown8;
    public long unknown9;

    static {
        LoginServerActionFactory.registerOutbound(P030_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  30;
    }

}
