
package gwlpr.actions.loginserver.outbound;

import gwlpr.actions.utils.IsArray;
import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P034_Unknown
    extends GenericAction
{

    private long unknown1;
    @IsArray(constant = true, size = 12, prefixLength = 1)
    private short[] unknown2;

    public short getHeader() {
        return  34;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(short[] unknown2) {
        this.unknown2 = unknown2;
    }

}
