
package gwlpr.protocol.loginserver.outbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P003_StreamTerminator
    extends GWAction
{

    private long loginCount;
    private long errorCode;

    @Override
    public short getHeader() {
        return  3;
    }

    public void setLoginCount(long loginCount) {
        this.loginCount = loginCount;
    }

    public void setErrorCode(long errorCode) {
        this.errorCode = errorCode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P003_StreamTerminator[");
        sb.append("loginCount=").append(this.loginCount).append(",errorCode=").append(this.errorCode).append("]");
        return sb.toString();
    }

}
