/**
 * For copyright information see the LICENSE document.
 */

/**
 * Auto-generated by PacketCodeGen, on 2012-05-28
 */

package com.gamerevision.gwlpr.actions.gameserver.stoc;

import com.realityshard.shardlet.GenericAction;
import java.nio.BufferOverflowException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.List;

/**
 * This is an automatically generated ShardletAction.
 * It resembles the packet template that has been 
 * parsed from our packet templates xml.
 *
 * Auto generated 
 *
 * @author GWLPR Template Updater
 */
public final class P061_UnknownAction extends GenericAction
{

    private int unknown1;
    private List<Float> unknown2;
    private short unknown3;
    private short unknown4;
    private int unknown5;
    private List<Short> unknown6;
    private List<Short> unknown7;
    private List<Short> unknown8;
    private short unknown9;


    public short getHeader()
    {
        return 61;
    }


    public void setUnknown1(int newValue)
    {
        unknown1 = newValue;
    }


    public void setUnknown2(List<Float> newValue)
    {
        unknown2 = newValue;
    }


    public void setUnknown3(short newValue)
    {
        unknown3 = newValue;
    }


    public void setUnknown4(short newValue)
    {
        unknown4 = newValue;
    }


    public void setUnknown5(int newValue)
    {
        unknown5 = newValue;
    }


    public void setUnknown6(List<Short> newValue)
    {
        unknown6 = newValue;
    }


    public void setUnknown7(List<Short> newValue)
    {
        unknown7 = newValue;
    }


    public void setUnknown8(List<Short> newValue)
    {
        unknown8 = newValue;
    }


    public void setUnknown9(short newValue)
    {
        unknown9 = newValue;
    }


    private int getSize()
    {
        int size = 30;

        if (unknown2.size() != 2)
        {
            return 0;
        }
        if (unknown6 == null)
        {
            return 0;
        }
        
        size += 2 * unknown6.size();
        if (unknown7 == null)
        {
            return 0;
        }
        
        size += 2 * unknown7.size();
        if (unknown8 == null)
        {
            return 0;
        }
        
        size += 2 * unknown8.size();

        return size;
    }


    @Override
    public boolean serialize()
    {
        int size = getSize();

        if (size == 0)
        {
            return false;
        }

        ByteBuffer buffer = ByteBuffer.allocate(size).order(ByteOrder.LITTLE_ENDIAN);

        try
        {
            buffer.putShort(getHeader());

            buffer.putInt(unknown1);
            buffer.putFloat(unknown2.get(0));
            buffer.putFloat(unknown2.get(1));
            buffer.putShort(unknown3);
            buffer.putShort(unknown4);
            buffer.putInt(unknown5);
            short prefix_unknown6 = (short) unknown6.size();
            buffer.putShort(prefix_unknown6);
            
            for (int i = 0; i < prefix_unknown6; i++)
            {
                buffer.putShort(unknown6.get(i));
            }
            short prefix_unknown7 = (short) unknown7.size();
            buffer.putShort(prefix_unknown7);
            
            for (int i = 0; i < prefix_unknown7; i++)
            {
                buffer.putShort(unknown7.get(i));
            }
            short prefix_unknown8 = (short) unknown8.size();
            buffer.putShort(prefix_unknown8);
            
            for (int i = 0; i < prefix_unknown8; i++)
            {
                buffer.putShort(unknown8.get(i));
            }
            buffer.putShort(unknown9);
        }
        catch (BufferOverflowException e)
        {
            return false;
        }

        setBuffer(buffer);

        return true;
    }
}