/**
 * For copyright information see the LICENSE document.
 */

/**
 * Auto-generated by PacketCodeGen, on 2012-05-28
 */

package com.gamerevision.gwlpr.actions.gameserver.stoc;

import com.realityshard.shardlet.GenericAction;
import java.nio.BufferOverflowException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.List;

/**
 * This is an automatically generated ShardletAction.
 * It resembles the packet template that has been 
 * parsed from our packet templates xml.
 *
 * Auto generated 
 *
 * @author GWLPR Template Updater
 */
public final class P136_UnknownAction extends GenericAction
{

    private List<Integer> unknown1;
    private List<Integer> unknown2;
    private List<Integer> unknown3;
    private List<Integer> unknown4;
    private List<Integer> unknown5;


    public short getHeader()
    {
        return 136;
    }


    public void setUnknown1(List<Integer> newValue)
    {
        unknown1 = newValue;
    }


    public void setUnknown2(List<Integer> newValue)
    {
        unknown2 = newValue;
    }


    public void setUnknown3(List<Integer> newValue)
    {
        unknown3 = newValue;
    }


    public void setUnknown4(List<Integer> newValue)
    {
        unknown4 = newValue;
    }


    public void setUnknown5(List<Integer> newValue)
    {
        unknown5 = newValue;
    }


    private int getSize()
    {
        int size = 12;

        if (unknown1 == null)
        {
            return 0;
        }
        
        size += 4 * unknown1.size();
        if (unknown2 == null)
        {
            return 0;
        }
        
        size += 4 * unknown2.size();
        if (unknown3 == null)
        {
            return 0;
        }
        
        size += 4 * unknown3.size();
        if (unknown4 == null)
        {
            return 0;
        }
        
        size += 4 * unknown4.size();
        if (unknown5 == null)
        {
            return 0;
        }
        
        size += 4 * unknown5.size();

        return size;
    }


    @Override
    public boolean serialize()
    {
        int size = getSize();

        if (size == 0)
        {
            return false;
        }

        ByteBuffer buffer = ByteBuffer.allocate(size).order(ByteOrder.LITTLE_ENDIAN);

        try
        {
            buffer.putShort(getHeader());

            short prefix_unknown1 = (short) unknown1.size();
            buffer.putShort(prefix_unknown1);
            
            for (int i = 0; i < prefix_unknown1; i++)
            {
                buffer.putInt(unknown1.get(i));
            }
            short prefix_unknown2 = (short) unknown2.size();
            buffer.putShort(prefix_unknown2);
            
            for (int i = 0; i < prefix_unknown2; i++)
            {
                buffer.putInt(unknown2.get(i));
            }
            short prefix_unknown3 = (short) unknown3.size();
            buffer.putShort(prefix_unknown3);
            
            for (int i = 0; i < prefix_unknown3; i++)
            {
                buffer.putInt(unknown3.get(i));
            }
            short prefix_unknown4 = (short) unknown4.size();
            buffer.putShort(prefix_unknown4);
            
            for (int i = 0; i < prefix_unknown4; i++)
            {
                buffer.putInt(unknown4.get(i));
            }
            short prefix_unknown5 = (short) unknown5.size();
            buffer.putShort(prefix_unknown5);
            
            for (int i = 0; i < prefix_unknown5; i++)
            {
                buffer.putInt(unknown5.get(i));
            }
        }
        catch (BufferOverflowException e)
        {
            return false;
        }

        setBuffer(buffer);

        return true;
    }
}