
package gwlpr.actions.loginserver.inbound;

import gwlpr.actions.utils.IsArray;
import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P003_Unknown
    extends GenericAction
{

    private long unknown1;
    private String unknown2;
    @IsArray(constant = true, size = 20, prefixLength = 1)
    private short[] unknown3;
    private String unknown4;

    public short getHeader() {
        return  3;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public String getUnknown2() {
        return unknown2;
    }

    public short[] getUnknown3() {
        return unknown3;
    }

    public String getUnknown4() {
        return unknown4;
    }

}
