
package gwlpr.actions.loginserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.IsArray;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P009_Unknown
    extends GWAction
{

    public long unknown1;
    public String unknown2;
    @IsArray(constant = false, size = 64, prefixLength = 2)
    public byte[] unknown3;

    @Override
    public short getHeader() {
        return  9;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public String getUnknown2() {
        return unknown2;
    }

    public byte[] getUnknown3() {
        return unknown3;
    }

}
