
package gwlpr.actions.loginserver.inbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P012_Unknown
    extends GenericAction
{

    private long unknown1;
    private long unknown2;
    private String unknown3;

    public short getHeader() {
        return  12;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public long getUnknown2() {
        return unknown2;
    }

    public String getUnknown3() {
        return unknown3;
    }

}
