
package gwlpr.actions.loginserver.inbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P017_Unknown
    extends GenericAction
{

    private String unknown1;

    public short getHeader() {
        return  17;
    }

    public String getUnknown1() {
        return unknown1;
    }

}
