
package gwlpr.actions.loginserver.inbound;

import gwlpr.actions.utils.IsArray;
import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P018_Unknown
    extends GenericAction
{

    private long unknown1;
    private long unknown2;
    @IsArray(constant = true, size = 20, prefixLength = 1)
    private short[] unknown3;
    private String unknown4;
    private String unknown5;
    private String unknown6;
    private String unknown7;

    public short getHeader() {
        return  18;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public long getUnknown2() {
        return unknown2;
    }

    public short[] getUnknown3() {
        return unknown3;
    }

    public String getUnknown4() {
        return unknown4;
    }

    public String getUnknown5() {
        return unknown5;
    }

    public String getUnknown6() {
        return unknown6;
    }

    public String getUnknown7() {
        return unknown7;
    }

}
