
package gwlpr.actions.loginserver.inbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P020_Unknown
    extends GWAction
{

    public long unknown1;
    public long unknown2;
    public String unknown3;
    public String unknown4;
    public String unknown5;

    @Override
    public short getHeader() {
        return  20;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public long getUnknown2() {
        return unknown2;
    }

    public String getUnknown3() {
        return unknown3;
    }

    public String getUnknown4() {
        return unknown4;
    }

    public String getUnknown5() {
        return unknown5;
    }

}
