
package gwlpr.actions.loginserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.loginserver.LoginServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P028_Unknown
    extends GWAction
{

    public long unknown1;
    public String unknown2;

    static {
        LoginServerActionFactory.registerInbound(P028_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  28;
    }

}
