
package gwlpr.actions.loginserver.inbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P030_Unknown
    extends GWAction
{

    public long unknown1;
    public long unknown2;
    public String unknown3;

    @Override
    public short getHeader() {
        return  30;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public long getUnknown2() {
        return unknown2;
    }

    public String getUnknown3() {
        return unknown3;
    }

}
