
package gwlpr.actions.loginserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.utils.IsArray;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P037_Unknown
    extends GWAction
{

    public long unknown1;
    public long unknown2;
    public long unknown3;
    public long unknown4;
    public long unknown5;
    @IsArray(constant = true, size = 16, prefixLength = -1)
    public byte[] unknown6;

    @Override
    public short getHeader() {
        return  37;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public long getUnknown2() {
        return unknown2;
    }

    public long getUnknown3() {
        return unknown3;
    }

    public long getUnknown4() {
        return unknown4;
    }

    public long getUnknown5() {
        return unknown5;
    }

    public byte[] getUnknown6() {
        return unknown6;
    }

}
