
package gwlpr.actions.loginserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.loginserver.LoginServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P041_CharacterPlayInfo
    extends GWAction
{

    public long loginCount;
    public long unknown1;
    public long gameMapId;
    public long unknown2;
    public long unknown3;
    public long unknown4;

    static {
        LoginServerActionFactory.registerInbound(P041_CharacterPlayInfo.class);
    }

    @Override
    public short getHeader() {
        return  41;
    }

}
