
package gwlpr.actions.loginserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.loginserver.LoginServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P046_Unknown
    extends GWAction
{


    static {
        LoginServerActionFactory.registerInbound(P046_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  46;
    }

}
