
package gwlpr.actions.loginserver.inbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P047_Unknown
    extends GenericAction
{


    public short getHeader() {
        return  47;
    }

}
