
package gwlpr.actions.loginserver.inbound;

import gwlpr.actions.utils.IsArray;
import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P054_Unknown
    extends GenericAction
{

    private long unknown1;
    private long unknown2;
    private long unknown3;
    private long unknown4;
    private long unknown5;
    private long unknown6;
    @IsArray(constant = true, size = 256, prefixLength = 1)
    private short[] unknown7;
    private String unknown8;
    private String unknown9;
    private String unknown10;
    private String unknown11;
    private String unknown12;
    private String unknown13;
    private String unknown14;
    private String unknown15;
    private String unknown16;
    private String unknown17;
    private String unknown18;
    private String unknown19;
    private String unknown20;
    @IsArray(constant = false, size = 128, prefixLength = 2)
    private long[] unknown21;
    @IsArray(constant = false, size = 128, prefixLength = 2)
    private long[] unknown22;

    public short getHeader() {
        return  54;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public long getUnknown2() {
        return unknown2;
    }

    public long getUnknown3() {
        return unknown3;
    }

    public long getUnknown4() {
        return unknown4;
    }

    public long getUnknown5() {
        return unknown5;
    }

    public long getUnknown6() {
        return unknown6;
    }

    public short[] getUnknown7() {
        return unknown7;
    }

    public String getUnknown8() {
        return unknown8;
    }

    public String getUnknown9() {
        return unknown9;
    }

    public String getUnknown10() {
        return unknown10;
    }

    public String getUnknown11() {
        return unknown11;
    }

    public String getUnknown12() {
        return unknown12;
    }

    public String getUnknown13() {
        return unknown13;
    }

    public String getUnknown14() {
        return unknown14;
    }

    public String getUnknown15() {
        return unknown15;
    }

    public String getUnknown16() {
        return unknown16;
    }

    public String getUnknown17() {
        return unknown17;
    }

    public String getUnknown18() {
        return unknown18;
    }

    public String getUnknown19() {
        return unknown19;
    }

    public String getUnknown20() {
        return unknown20;
    }

    public long[] getUnknown21() {
        return unknown21;
    }

    public long[] getUnknown22() {
        return unknown22;
    }

}
