
package gwlpr.actions.loginserver.inbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P055_Unknown
    extends GWAction
{

    public long unknown1;
    public String unknown2;
    public String unknown3;

    @Override
    public short getHeader() {
        return  55;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public String getUnknown2() {
        return unknown2;
    }

    public String getUnknown3() {
        return unknown3;
    }

}
