/**
 * For copyright information see the LICENSE document.
 */

/**
 * Auto-generated by PacketCodeGen, on 2012-05-28
 */

package com.gamerevision.gwlpr.gwprotocol.actions.loginserver.ctos;

import com.realityshard.shardlet.EventAggregator;
import com.realityshard.shardlet.GenericEventAction;
import java.nio.BufferUnderflowException;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.List;

/**
 * This is an automatically generated ShardletAction.
 * It resembles the packet template that has been 
 * parsed from our packet templates xml.
 *
 * Auto generated 
 *
 * @author GWLPR Template Updater
 */
public final class P020_UnknownAction extends GenericEventAction
{

    private int unknown1;
    private int unknown2;
    private List<Short> unknown3;
    private List<Short> unknown4;
    private List<Short> unknown5;


    public short getHeader()
    {
        return 20;
    }


    public int getUnknown1()
    {
        return unknown1;
    }


    public int getUnknown2()
    {
        return unknown2;
    }


    public List<Short> getUnknown3()
    {
        return unknown3;
    }


    public List<Short> getUnknown4()
    {
        return unknown4;
    }


    public List<Short> getUnknown5()
    {
        return unknown5;
    }


    @Override
    public boolean deserialize()
    {
        ByteBuffer buffer = getBuffer();
        int bufferPosition = buffer.position();

        try
        {
            unknown1 = buffer.getInt();
            unknown2 = buffer.getInt();
            short prefix_unknown3 = buffer.getShort();
            unknown3 = new ArrayList<>();
            
            for (int i = 0; i < prefix_unknown3; i++)
            {
                unknown3.add(buffer.getShort());
            }
            short prefix_unknown4 = buffer.getShort();
            unknown4 = new ArrayList<>();
            
            for (int i = 0; i < prefix_unknown4; i++)
            {
                unknown4.add(buffer.getShort());
            }
            short prefix_unknown5 = buffer.getShort();
            unknown5 = new ArrayList<>();
            
            for (int i = 0; i < prefix_unknown5; i++)
            {
                unknown5.add(buffer.getShort());
            }
        }
        catch (BufferUnderflowException e)
        {
            buffer.position(bufferPosition);
            return false;
        }

        return true;
    }


    @Override
    public void triggerEvent(EventAggregator aggregator)
    {
        aggregator.triggerEvent(this);
    }
}