/**
 * For copyright information see the LICENSE document.
 */

/**
 * Auto-generated by PacketCodeGen, on 2012-09-28
 */

package com.gamerevision.gwlpr.actions.gameserver.ctos;

import com.realityshard.shardlet.EventAggregator;
import com.realityshard.shardlet.utils.GenericTriggerableAction;
import java.nio.BufferUnderflowException;
import java.nio.ByteBuffer;

/**
 * This is an automatically generated ShardletAction.
 * It resembles the packet template that has been 
 * parsed from our packet templates xml.
 *
 * Auto generated 
 *
 * @author GWLPR Template Updater
 */
public final class P163_UnknownAction extends GenericTriggerableAction
{

    private byte unknown1;
    private char[] unknown2;
    private short unknown3;


    public short getHeader()
    {
        return 163;
    }


    public byte getUnknown1()
    {
        return unknown1;
    }


    public char[] getUnknown2()
    {
        return unknown2;
    }


    public short getUnknown3()
    {
        return unknown3;
    }


    @Override
    public boolean deserialize()
    {
        ByteBuffer buffer = getBuffer();
        int bufferPosition = buffer.position();

        try
        {
            unknown1 = buffer.get();
            short prefix_unknown2 = buffer.getShort();
            unknown2 = new char[prefix_unknown2];
            
            for (int i = 0; i < prefix_unknown2; i++)
            {
                unknown2[i] = buffer.getChar();
            }
            unknown3 = buffer.getShort();
        }
        catch (BufferUnderflowException e)
        {
            buffer.position(bufferPosition);
            return false;
        }

        return true;
    }


    @Override
    public void triggerEvent(EventAggregator aggregator)
    {
        aggregator.triggerEvent(this);
    }
}