/**
 * For copyright information see the LICENSE document.
 */

package gwlpr.protocol.handshake;

import gwlpr.protocol.serialization.GWMessage;
import gwlpr.protocol.util.IsArray;


/**
 * Generated by hand :P
 * This packet has actually its own length as a header.
 * 
 * @author _rusty
 */
public class OUT_ServerSeed
    extends GWMessage
{
    @IsArray(constant=true, size=20, prefixLength = -1)
    private byte[] encryptedRC4Key;

    @Override
    public short getHeader() {
        return 5633;
    }

    public void setEncryptedRC4Key(byte[] encryptedRC4Key) {
        this.encryptedRC4Key = encryptedRC4Key;
    }
}
