
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P014_Unknown
    extends GWAction
{

    public long agentID1;
    public long agentID2;

    @Override
    public short getHeader() {
        return  14;
    }

    public long getAgentID1() {
        return agentID1;
    }

    public long getAgentID2() {
        return agentID2;
    }

}
