
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P018_Unknown
    extends GWAction
{

    public long agentID1;
    public Vector2 unknown2;
    public long unknown3;

    static {
        GameServerActionFactory.registerInbound(P018_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  18;
    }

}
