
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P021_Unknown
    extends GWAction
{

    public long agentID1;
    public long unknown2;
    public long unknown3;

    static {
        GameServerActionFactory.registerInbound(P021_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  21;
    }

}
