
package gwlpr.actions.gameserver.inbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P027_Unknown
    extends GenericAction
{

    private short unknown1;
    private long unknown2;

    public short getHeader() {
        return  27;
    }

    public short getUnknown1() {
        return unknown1;
    }

    public long getUnknown2() {
        return unknown2;
    }

}
