
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P046_Unknown
    extends GWAction
{

    public long unknown1;
    public short unknown2;
    public long unknown3;

    static {
        GameServerActionFactory.registerInbound(P046_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  46;
    }

}
