
package gwlpr.actions.gameserver.inbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P049_Unknown
    extends GenericAction
{

    private long unknown1;
    private short unknown2;
    private short unknown3;
    private short unknown4;
    private short unknown5;
    private short unknown6;
    private int unknown7;
    private short unknown8;

    public short getHeader() {
        return  49;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public short getUnknown2() {
        return unknown2;
    }

    public short getUnknown3() {
        return unknown3;
    }

    public short getUnknown4() {
        return unknown4;
    }

    public short getUnknown5() {
        return unknown5;
    }

    public short getUnknown6() {
        return unknown6;
    }

    public int getUnknown7() {
        return unknown7;
    }

    public short getUnknown8() {
        return unknown8;
    }

}
