
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P049_Unknown
    extends GWAction
{

    public long unknown1;
    public short unknown2;
    public short unknown3;
    public short unknown4;
    public short unknown5;
    public short unknown6;
    public int unknown7;
    public short unknown8;

    @Override
    public short getHeader() {
        return  49;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public short getUnknown2() {
        return unknown2;
    }

    public short getUnknown3() {
        return unknown3;
    }

    public short getUnknown4() {
        return unknown4;
    }

    public short getUnknown5() {
        return unknown5;
    }

    public short getUnknown6() {
        return unknown6;
    }

    public int getUnknown7() {
        return unknown7;
    }

    public short getUnknown8() {
        return unknown8;
    }

}
