
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P050_Unknown
    extends GWAction
{

    public long agentID1;
    public short unknown2;

    static {
        GameServerActionFactory.registerInbound(P050_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  50;
    }

}
