
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P058_ChangeSecondProfession
    extends GWAction
{

    public long agentID;
    public short profession;

    @Override
    public short getHeader() {
        return  58;
    }

    public long getAgentID() {
        return agentID;
    }

    public short getProfession() {
        return profession;
    }

}
