
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P058_ChangeSecondProfession
    extends GWAction
{

    public long agentID;
    public short profession;

    static {
        GameServerActionFactory.registerInbound(P058_ChangeSecondProfession.class);
    }

    @Override
    public short getHeader() {
        return  58;
    }

}
