
package gwlpr.actions.gameserver.inbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P061_Unknown
    extends GenericAction
{

    private long unknown1;

    public short getHeader() {
        return  61;
    }

    public long getUnknown1() {
        return unknown1;
    }

}
