
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P064_Unknown
    extends GWAction
{

    public Vector2 unknown1;
    public long unknown2;

    static {
        GameServerActionFactory.registerInbound(P064_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  64;
    }

}
