
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.utils.IsArray;
import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P069_Unknown
    extends GenericAction
{

    private short unknown1;
    private short unknown2;
    private long unknown3;
    @IsArray(constant = false, size = 16, prefixLength = 2)
    private long[] unknown4;
    private long unknown5;
    @IsArray(constant = false, size = 16, prefixLength = 2)
    private long[] unknown6;

    public short getHeader() {
        return  69;
    }

    public short getUnknown1() {
        return unknown1;
    }

    public short getUnknown2() {
        return unknown2;
    }

    public long getUnknown3() {
        return unknown3;
    }

    public long[] getUnknown4() {
        return unknown4;
    }

    public long getUnknown5() {
        return unknown5;
    }

    public long[] getUnknown6() {
        return unknown6;
    }

}
