
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.utils.IsArray;
import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P070_Unknown
    extends GenericAction
{

    private short unknown1;
    private long unknown2;
    @IsArray(constant = false, size = 16, prefixLength = 2)
    private long[] unknown3;
    @IsArray(constant = false, size = 16, prefixLength = 1)
    private short[] unknown4;
    private long unknown5;
    @IsArray(constant = false, size = 16, prefixLength = 2)
    private long[] unknown6;
    @IsArray(constant = false, size = 16, prefixLength = 1)
    private short[] unknown7;

    public short getHeader() {
        return  70;
    }

    public short getUnknown1() {
        return unknown1;
    }

    public long getUnknown2() {
        return unknown2;
    }

    public long[] getUnknown3() {
        return unknown3;
    }

    public short[] getUnknown4() {
        return unknown4;
    }

    public long getUnknown5() {
        return unknown5;
    }

    public long[] getUnknown6() {
        return unknown6;
    }

    public short[] getUnknown7() {
        return unknown7;
    }

}
