
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P071_Unknown
    extends GWAction
{

    public short unknown1;
    public String unknown2;

    static {
        GameServerActionFactory.registerInbound(P071_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  71;
    }

}
