
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P074_Unknown
    extends GWAction
{

    public long agentID1;
    public short unknown2;

    @Override
    public short getHeader() {
        return  74;
    }

    public long getAgentID1() {
        return agentID1;
    }

    public short getUnknown2() {
        return unknown2;
    }

}
