
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P087_Unknown
    extends GWAction
{

    public long agentID1;
    public long unknown2;
    public long unknown3;
    public long unknown4;

    static {
        GameServerActionFactory.registerInbound(P087_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  87;
    }

}
