
package gwlpr.actions.gameserver.inbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P090_Unknown
    extends GenericAction
{

    private String unknown1;
    private short unknown2;

    public short getHeader() {
        return  90;
    }

    public String getUnknown1() {
        return unknown1;
    }

    public short getUnknown2() {
        return unknown2;
    }

}
