
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P100_Unknown
    extends GWAction
{

    public long unknown1;
    public short unknown2;

    @Override
    public short getHeader() {
        return  100;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public short getUnknown2() {
        return unknown2;
    }

}
