
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.utils.IsArray;
import gwlpr.actions.utils.NestedMarker;
import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P106_Unknown
    extends GenericAction
{

    private short unknown1;
    @IsArray(constant = false, size = 6, prefixLength = 2)
    private P106_Unknown.NestedUnknown2 [] unknown2;

    public short getHeader() {
        return  106;
    }

    public short getUnknown1() {
        return unknown1;
    }

    public P106_Unknown.NestedUnknown2 [] getUnknown2() {
        return unknown2;
    }

    public final class NestedUnknown2
        implements NestedMarker
    {

        private short unknown1;
        private long unknown2;

    }

}
