
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.IsArray;
import gwlpr.actions.utils.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P106_Unknown
    extends GWAction
{

    public short unknown1;
    @IsArray(constant = false, size = 6, prefixLength = 2)
    public P106_Unknown.NestedUnknown2 [] unknown2;

    static {
        GameServerActionFactory.registerInbound(P106_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  106;
    }

    public final static class NestedUnknown2
        implements NestedMarker
    {

        public short unknown1;
        public long unknown2;

    }

}
