
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P112_Unknown
    extends GWAction
{

    public int unknown1;
    public long unknown2;
    public long unknown3;

    static {
        GameServerActionFactory.registerInbound(P112_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  112;
    }

}
