
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P122_Unknown
    extends GWAction
{


    @Override
    public short getHeader() {
        return  122;
    }

}
