
package gwlpr.actions.gameserver.inbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P134_Unknown
    extends GenericAction
{

    private int unknown1;
    private short unknown2;

    public short getHeader() {
        return  134;
    }

    public int getUnknown1() {
        return unknown1;
    }

    public short getUnknown2() {
        return unknown2;
    }

}
