
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P134_Unknown
    extends GWAction
{

    public int unknown1;
    public short unknown2;

    @Override
    public short getHeader() {
        return  134;
    }

    public int getUnknown1() {
        return unknown1;
    }

    public short getUnknown2() {
        return unknown2;
    }

}
