
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.utils.IsArray;
import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P139_Unknown
    extends GenericAction
{

    @IsArray(constant = false, size = 112, prefixLength = 1)
    private short[] unknown1;

    public short getHeader() {
        return  139;
    }

    public short[] getUnknown1() {
        return unknown1;
    }

}
