
package gwlpr.actions.gameserver.inbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P149_Unknown
    extends GenericAction
{

    private int unknown1;

    public short getHeader() {
        return  149;
    }

    public int getUnknown1() {
        return unknown1;
    }

}
