
package gwlpr.actions.gameserver.inbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P154_Unknown
    extends GenericAction
{

    private String unknown1;

    public short getHeader() {
        return  154;
    }

    public String getUnknown1() {
        return unknown1;
    }

}
