
package gwlpr.actions.gameserver.inbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P156_Unknown
    extends GenericAction
{


    public short getHeader() {
        return  156;
    }

}
