
package gwlpr.actions.gameserver.inbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P158_Unknown
    extends GenericAction
{

    private short unknown1;

    public short getHeader() {
        return  158;
    }

    public short getUnknown1() {
        return unknown1;
    }

}
