
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P159_Unknown
    extends GWAction
{

    public int unknown1;
    public long unknown2;
    public short unknown3;

    static {
        GameServerActionFactory.registerInbound(P159_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  159;
    }

}
