
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P159_Unknown
    extends GWAction
{

    public int unknown1;
    public long unknown2;
    public short unknown3;

    @Override
    public short getHeader() {
        return  159;
    }

    public int getUnknown1() {
        return unknown1;
    }

    public long getUnknown2() {
        return unknown2;
    }

    public short getUnknown3() {
        return unknown3;
    }

}
