
package gwlpr.actions.gameserver.inbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P160_Unknown
    extends GenericAction
{


    public short getHeader() {
        return  160;
    }

}
