
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P168_Unknown
    extends GWAction
{

    public short unknown1;

    static {
        GameServerActionFactory.registerInbound(P168_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  168;
    }

}
