
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.IsArray;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P169_Unknown
    extends GWAction
{

    @IsArray(constant = true, size = 16, prefixLength = -1)
    public byte[] unknown1;
    public short unknown2;

    static {
        GameServerActionFactory.registerInbound(P169_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  169;
    }

}
