
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P170_Unknown
    extends GWAction
{

    public int unknown1;
    public short unknown2;
    public int unknown3;
    public short unknown4;
    public short unknown5;

    @Override
    public short getHeader() {
        return  170;
    }

    public int getUnknown1() {
        return unknown1;
    }

    public short getUnknown2() {
        return unknown2;
    }

    public int getUnknown3() {
        return unknown3;
    }

    public short getUnknown4() {
        return unknown4;
    }

    public short getUnknown5() {
        return unknown5;
    }

}
