
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P170_Unknown
    extends GWAction
{

    public int unknown1;
    public short unknown2;
    public int unknown3;
    public short unknown4;
    public short unknown5;

    static {
        GameServerActionFactory.registerInbound(P170_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  170;
    }

}
