
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P173_Unknown
    extends GWAction
{


    static {
        GameServerActionFactory.registerInbound(P173_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  173;
    }

}
