
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P180_Unknown
    extends GWAction
{

    public long unknown1;
    public String unknown2;

    static {
        GameServerActionFactory.registerInbound(P180_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  180;
    }

}
