
package gwlpr.actions.gameserver.inbound;

import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P182_Unknown
    extends GenericAction
{

    private long unknown1;
    private String unknown2;
    private short unknown3;

    public short getHeader() {
        return  182;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public String getUnknown2() {
        return unknown2;
    }

    public short getUnknown3() {
        return unknown3;
    }

}
