
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.GWAction;
import gwlpr.actions.gameserver.GameServerActionFactory;
import gwlpr.actions.utils.IsArray;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P184_Unknown
    extends GWAction
{

    public long unknown1;
    @IsArray(constant = true, size = 16, prefixLength = -1)
    public byte[] unknown2;
    public short unknown3;

    static {
        GameServerActionFactory.registerInbound(P184_Unknown.class);
    }

    @Override
    public short getHeader() {
        return  184;
    }

}
