
package gwlpr.actions.gameserver.inbound;

import gwlpr.actions.utils.IsArray;
import realityshard.shardlet.utils.GenericAction;


/**
 * Auto-generated by "Packet generator".
 * 
 * 
 */
public final class P184_Unknown
    extends GenericAction
{

    private long unknown1;
    @IsArray(constant = true, size = 16, prefixLength = 1)
    private short[] unknown2;
    private short unknown3;

    public short getHeader() {
        return  184;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public short[] getUnknown2() {
        return unknown2;
    }

    public short getUnknown3() {
        return unknown3;
    }

}
