
package gwlpr.protocol.loginserver.inbound;

import java.util.UUID;
import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P002_UnknownLoginState
    extends GWMessage
{

    private long loginCount;
    private UUID accountUID;

    @Override
    public short getHeader() {
        return  2;
    }

    public long getLoginCount() {
        return loginCount;
    }

    public UUID getAccountUID() {
        return accountUID;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P002_UnknownLoginState[");
        sb.append("loginCount=").append(this.loginCount).append(",accountUID=").append(this.accountUID.toString()).append("]");
        return sb.toString();
    }

}
