
package gwlpr.protocol.loginserver.inbound;

import java.util.Arrays;
import gwlpr.protocol.serialization.GWAction;
import gwlpr.protocol.util.IsArray;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P015_Unknown
    extends GWAction
{

    @IsArray(constant = false, size = 92, prefixLength = 2)
    private byte[] unknown1;
    @IsArray(constant = true, size = 16, prefixLength = -1)
    private byte[] unknown2;

    @Override
    public short getHeader() {
        return  15;
    }

    public byte[] getUnknown1() {
        return unknown1;
    }

    public byte[] getUnknown2() {
        return unknown2;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P015_Unknown[");
        sb.append("unknown1=").append(Arrays.toString(this.unknown1)).append(",unknown2=").append(Arrays.toString(this.unknown2)).append("]");
        return sb.toString();
    }

}
