
package gwlpr.protocol.loginserver.inbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P027_Unknown
    extends GWAction
{

    private long unknown1;
    private String unknown2;
    private String unknown3;

    @Override
    public short getHeader() {
        return  27;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public String getUnknown2() {
        return unknown2;
    }

    public String getUnknown3() {
        return unknown3;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P027_Unknown[");
        sb.append("unknown1=").append(this.unknown1).append(",unknown2=").append(this.unknown2 .toString()).append(",unknown3=").append(this.unknown3 .toString()).append("]");
        return sb.toString();
    }

}
