
package gwlpr.protocol.loginserver.inbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P047_Unknown
    extends GWMessage
{


    @Override
    public short getHeader() {
        return  47;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P047_Unknown[");
        sb.append("]");
        return sb.toString();
    }

}
