
package gwlpr.protocol.loginserver.inbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P053_RequestResponse
    extends GWMessage
{

    private long loginCount;

    @Override
    public short getHeader() {
        return  53;
    }

    public long getLoginCount() {
        return loginCount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P053_RequestResponse[");
        sb.append("loginCount=").append(this.loginCount).append("]");
        return sb.toString();
    }

}
