/**
 * For copyright information see the LICENSE document.
 */

/**
 * Auto-generated by PacketCodeGen, on 2012-05-28
 */

package com.gamerevision.gwlpr.gwprotocol.actions.gameserver.ctos;

import com.realityshard.shardlet.EventAggregator;
import com.realityshard.shardlet.GenericEventAction;
import java.nio.BufferUnderflowException;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.List;

/**
 * This is an automatically generated ShardletAction.
 * It resembles the packet template that has been 
 * parsed from our packet templates xml.
 *
 * Auto generated 
 *
 * @author GWLPR Template Updater
 */
public final class P069_UnknownAction extends GenericEventAction
{

    private byte unknown1;
    private byte unknown2;
    private int unknown3;
    private List<Integer> unknown4;
    private int unknown5;
    private List<Integer> unknown6;


    public short getHeader()
    {
        return 69;
    }


    public byte getUnknown1()
    {
        return unknown1;
    }


    public byte getUnknown2()
    {
        return unknown2;
    }


    public int getUnknown3()
    {
        return unknown3;
    }


    public List<Integer> getUnknown4()
    {
        return unknown4;
    }


    public int getUnknown5()
    {
        return unknown5;
    }


    public List<Integer> getUnknown6()
    {
        return unknown6;
    }


    @Override
    public boolean deserialize()
    {
        ByteBuffer buffer = getBuffer();
        int bufferPosition = buffer.position();

        try
        {
            unknown1 = buffer.get();
            unknown2 = buffer.get();
            unknown3 = buffer.getInt();
            short prefix_unknown4 = buffer.getShort();
            unknown4 = new ArrayList<>();
            
            for (int i = 0; i < prefix_unknown4; i++)
            {
                unknown4.add(buffer.getInt());
            }
            unknown5 = buffer.getInt();
            short prefix_unknown6 = buffer.getShort();
            unknown6 = new ArrayList<>();
            
            for (int i = 0; i < prefix_unknown6; i++)
            {
                unknown6.add(buffer.getInt());
            }
        }
        catch (BufferUnderflowException e)
        {
            buffer.position(bufferPosition);
            return false;
        }

        return true;
    }


    @Override
    public void triggerEvent(EventAggregator aggregator)
    {
        aggregator.triggerEvent(this);
    }
}