
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;
import gwlpr.protocol.util.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P021_SpawnAgent
    extends GWMessage
{

    private long agentID;
    /**
     * 
     * This field is a composite of: (factionColor
     * leftbitshift 24) | (localID)
     * 
     */
    private long facColorLocalID;
    private short unknown1;
    private short unknown2;
    private Vector2 positionVector;
    private int positionPlane;
    private Vector2 directionRotation;
    private short unknown3;
    private float moveSpeed;
    private float unknown4;
    private long unknown5;
    private long spawnType;
    private long unknown6;
    private long unknown7;
    private long unknown8;
    private long unknown9;
    private long unknown10;
    private Vector2 unknown11;
    private Vector2 unknown12;
    private int unknown13;
    private long unknown14;
    private Vector2 unknown15;
    private int unknown16;

    @Override
    public short getHeader() {
        return  21;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setFacColorLocalID(long facColorLocalID) {
        this.facColorLocalID = facColorLocalID;
    }

    public void setUnknown1(short unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(short unknown2) {
        this.unknown2 = unknown2;
    }

    public void setPositionVector(Vector2 positionVector) {
        this.positionVector = positionVector;
    }

    public void setPositionPlane(int positionPlane) {
        this.positionPlane = positionPlane;
    }

    public void setDirectionRotation(Vector2 directionRotation) {
        this.directionRotation = directionRotation;
    }

    public void setUnknown3(short unknown3) {
        this.unknown3 = unknown3;
    }

    public void setMoveSpeed(float moveSpeed) {
        this.moveSpeed = moveSpeed;
    }

    public void setUnknown4(float unknown4) {
        this.unknown4 = unknown4;
    }

    public void setUnknown5(long unknown5) {
        this.unknown5 = unknown5;
    }

    public void setSpawnType(long spawnType) {
        this.spawnType = spawnType;
    }

    public void setUnknown6(long unknown6) {
        this.unknown6 = unknown6;
    }

    public void setUnknown7(long unknown7) {
        this.unknown7 = unknown7;
    }

    public void setUnknown8(long unknown8) {
        this.unknown8 = unknown8;
    }

    public void setUnknown9(long unknown9) {
        this.unknown9 = unknown9;
    }

    public void setUnknown10(long unknown10) {
        this.unknown10 = unknown10;
    }

    public void setUnknown11(Vector2 unknown11) {
        this.unknown11 = unknown11;
    }

    public void setUnknown12(Vector2 unknown12) {
        this.unknown12 = unknown12;
    }

    public void setUnknown13(int unknown13) {
        this.unknown13 = unknown13;
    }

    public void setUnknown14(long unknown14) {
        this.unknown14 = unknown14;
    }

    public void setUnknown15(Vector2 unknown15) {
        this.unknown15 = unknown15;
    }

    public void setUnknown16(int unknown16) {
        this.unknown16 = unknown16;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P021_SpawnAgent[");
        sb.append("agentID=").append(this.agentID).append(",facColorLocalID=").append(this.facColorLocalID).append(",unknown1=").append(this.unknown1).append(",unknown2=").append(this.unknown2).append(",positionVector=").append(this.positionVector.toString()).append(",positionPlane=").append(this.positionPlane).append(",directionRotation=").append(this.directionRotation.toString()).append(",unknown3=").append(this.unknown3).append(",moveSpeed=").append(this.moveSpeed).append(",unknown4=").append(this.unknown4).append(",unknown5=").append(this.unknown5).append(",spawnType=").append(this.spawnType).append(",unknown6=").append(this.unknown6).append(",unknown7=").append(this.unknown7).append(",unknown8=").append(this.unknown8).append(",unknown9=").append(this.unknown9).append(",unknown10=").append(this.unknown10).append(",unknown11=").append(this.unknown11 .toString()).append(",unknown12=").append(this.unknown12 .toString()).append(",unknown13=").append(this.unknown13).append(",unknown14=").append(this.unknown14).append(",unknown15=").append(this.unknown15 .toString()).append(",unknown16=").append(this.unknown16).append("]");
        return sb.toString();
    }

}
