
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P022_DespawnAgent
    extends GWMessage
{

    /**
     * 
     * ID of the agent to despawn
     * 
     */
    private long agentID;

    @Override
    public short getHeader() {
        return  22;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P022_DespawnAgent[");
        sb.append("agentID=").append(this.agentID).append("]");
        return sb.toString();
    }

}
