
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P040_MessageOfTheDay
    extends GWMessage
{

    private String text;

    @Override
    public short getHeader() {
        return  40;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P040_MessageOfTheDay[");
        sb.append("text=").append(this.text.toString()).append("]");
        return sb.toString();
    }

}
