
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P060_DisplayCape
    extends GWAction
{

    private long agentID;
    private short display;

    @Override
    public short getHeader() {
        return  60;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setDisplay(short display) {
        this.display = display;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P060_DisplayCape[");
        sb.append("agentID=").append(this.agentID).append(",display=").append(this.display).append("]");
        return sb.toString();
    }

}
