
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P105_HeroDestroy
    extends GWMessage
{

    private long agentID;

    @Override
    public short getHeader() {
        return  105;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P105_HeroDestroy[");
        sb.append("agentID=").append(this.agentID).append("]");
        return sb.toString();
    }

}
