
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P107_HeroEnable
    extends GWAction
{

    private int heroID;

    @Override
    public short getHeader() {
        return  107;
    }

    public void setHeroID(int heroID) {
        this.heroID = heroID;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P107_HeroEnable[");
        sb.append("heroID=").append(this.heroID).append("]");
        return sb.toString();
    }

}
