
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P119_OpenDataWindow
    extends GWMessage
{

    private long agent;
    private short windowType;
    private long data;

    @Override
    public short getHeader() {
        return  119;
    }

    public void setAgent(long agent) {
        this.agent = agent;
    }

    public void setWindowType(short windowType) {
        this.windowType = windowType;
    }

    public void setData(long data) {
        this.data = data;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P119_OpenDataWindow[");
        sb.append("agent=").append(this.agent).append(",windowType=").append(this.windowType).append(",data=").append(this.data).append("]");
        return sb.toString();
    }

}
