
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;
import gwlpr.protocol.util.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P129_MissionMapIconAdd
    extends GWMessage
{

    private long localID;
    private Vector2 position;
    private int plane;
    private short color;
    private long unknown1;
    private long iconHash;
    private String text;

    @Override
    public short getHeader() {
        return  129;
    }

    public void setLocalID(long localID) {
        this.localID = localID;
    }

    public void setPosition(Vector2 position) {
        this.position = position;
    }

    public void setPlane(int plane) {
        this.plane = plane;
    }

    public void setColor(short color) {
        this.color = color;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

    public void setIconHash(long iconHash) {
        this.iconHash = iconHash;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P129_MissionMapIconAdd[");
        sb.append("localID=").append(this.localID).append(",position=").append(this.position.toString()).append(",plane=").append(this.plane).append(",color=").append(this.color).append(",unknown1=").append(this.unknown1).append(",iconHash=").append(this.iconHash).append(",text=").append(this.text.toString()).append("]");
        return sb.toString();
    }

}
