
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P131_MissionMapIconColor
    extends GWAction
{

    private long localID;
    private short color;

    @Override
    public short getHeader() {
        return  131;
    }

    public void setLocalID(long localID) {
        this.localID = localID;
    }

    public void setColor(short color) {
        this.color = color;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P131_MissionMapIconColor[");
        sb.append("localID=").append(this.localID).append(",color=").append(this.color).append("]");
        return sb.toString();
    }

}
