
package gwlpr.protocol.gameserver.outbound;

import java.util.Arrays;
import gwlpr.protocol.serialization.GWMessage;
import gwlpr.protocol.util.IsArray;
import gwlpr.protocol.util.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P136_Unknown
    extends GWMessage
{

    @IsArray(constant = false, size = 32, prefixLength = 2)
    private P136_Unknown.NestedUnknown1 [] unknown1;
    @IsArray(constant = false, size = 32, prefixLength = 2)
    private P136_Unknown.NestedUnknown2 [] unknown2;
    @IsArray(constant = false, size = 32, prefixLength = 2)
    private P136_Unknown.NestedUnknown3 [] unknown3;
    @IsArray(constant = false, size = 32, prefixLength = 2)
    private P136_Unknown.NestedUnknown4 [] unknown4;
    @IsArray(constant = false, size = 32, prefixLength = 2)
    private P136_Unknown.NestedUnknown5 [] unknown5;

    @Override
    public short getHeader() {
        return  136;
    }

    public void setUnknown1(P136_Unknown.NestedUnknown1 [] unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(P136_Unknown.NestedUnknown2 [] unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(P136_Unknown.NestedUnknown3 [] unknown3) {
        this.unknown3 = unknown3;
    }

    public void setUnknown4(P136_Unknown.NestedUnknown4 [] unknown4) {
        this.unknown4 = unknown4;
    }

    public void setUnknown5(P136_Unknown.NestedUnknown5 [] unknown5) {
        this.unknown5 = unknown5;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P136_Unknown[");
        sb.append("unknown1=").append(Arrays.toString(this.unknown1)).append(",unknown2=").append(Arrays.toString(this.unknown2)).append(",unknown3=").append(Arrays.toString(this.unknown3)).append(",unknown4=").append(Arrays.toString(this.unknown4)).append(",unknown5=").append(Arrays.toString(this.unknown5)).append("]");
        return sb.toString();
    }

    public final static class NestedUnknown1
        implements NestedMarker
    {

        private long unknown1;

        public void setUnknown1(long unknown1) {
            this.unknown1 = unknown1;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("NestedUnknown1[");
            sb.append("unknown1=").append(this.unknown1).append("]");
            return sb.toString();
        }

    }

    public final static class NestedUnknown2
        implements NestedMarker
    {

        private long unknown1;

        public void setUnknown1(long unknown1) {
            this.unknown1 = unknown1;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("NestedUnknown2[");
            sb.append("unknown1=").append(this.unknown1).append("]");
            return sb.toString();
        }

    }

    public final static class NestedUnknown3
        implements NestedMarker
    {

        private long unknown1;

        public void setUnknown1(long unknown1) {
            this.unknown1 = unknown1;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("NestedUnknown3[");
            sb.append("unknown1=").append(this.unknown1).append("]");
            return sb.toString();
        }

    }

    public final static class NestedUnknown4
        implements NestedMarker
    {

        private long unknown1;

        public void setUnknown1(long unknown1) {
            this.unknown1 = unknown1;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("NestedUnknown4[");
            sb.append("unknown1=").append(this.unknown1).append("]");
            return sb.toString();
        }

    }

    public final static class NestedUnknown5
        implements NestedMarker
    {

        private long unknown1;

        public void setUnknown1(long unknown1) {
            this.unknown1 = unknown1;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("NestedUnknown5[");
            sb.append("unknown1=").append(this.unknown1).append("]");
            return sb.toString();
        }

    }

}
