
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P143_UpdateNpcName
    extends GWAction
{

    private long agentID;
    private String name;

    @Override
    public short getHeader() {
        return  143;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P143_UpdateNpcName[");
        sb.append("agentID=").append(this.agentID).append(",name=").append(this.name.toString()).append("]");
        return sb.toString();
    }

}
