
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;
import gwlpr.protocol.util.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P149_PlayEffect
    extends GWMessage
{

    private Vector2 position;
    private int plane;
    private long agentID;
    private int effectID;
    private short unknown1;
    private short unknown2;

    @Override
    public short getHeader() {
        return  149;
    }

    public void setPosition(Vector2 position) {
        this.position = position;
    }

    public void setPlane(int plane) {
        this.plane = plane;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    public void setEffectID(int effectID) {
        this.effectID = effectID;
    }

    public void setUnknown1(short unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(short unknown2) {
        this.unknown2 = unknown2;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P149_PlayEffect[");
        sb.append("position=").append(this.position.toString()).append(",plane=").append(this.plane).append(",agentID=").append(this.agentID).append(",effectID=").append(this.effectID).append(",unknown1=").append(this.unknown1).append(",unknown2=").append(this.unknown2).append("]");
        return sb.toString();
    }

}
