
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P184_WindowOwner
    extends GWAction
{

    private long agentID;

    @Override
    public short getHeader() {
        return  184;
    }

    public void setAgentID(long agentID) {
        this.agentID = agentID;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P184_WindowOwner[");
        sb.append("agentID=").append(this.agentID).append("]");
        return sb.toString();
    }

}
