
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P222_UpdateMaxKurzickFaction
    extends GWMessage
{

    private long maxFaction;

    @Override
    public short getHeader() {
        return  222;
    }

    public void setMaxFaction(long maxFaction) {
        this.maxFaction = maxFaction;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P222_UpdateMaxKurzickFaction[");
        sb.append("maxFaction=").append(this.maxFaction).append("]");
        return sb.toString();
    }

}
