
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P226_ModifyFaction
    extends GWAction
{

    private long type;
    private long amount;

    @Override
    public short getHeader() {
        return  226;
    }

    public void setType(long type) {
        this.type = type;
    }

    public void setAmount(long amount) {
        this.amount = amount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P226_ModifyFaction[");
        sb.append("type=").append(this.type).append(",amount=").append(this.amount).append("]");
        return sb.toString();
    }

}
