
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P235_ItemPriceQuote
    extends GWAction
{

    private long itemLocalID;
    private long price;

    @Override
    public short getHeader() {
        return  235;
    }

    public void setItemLocalID(long itemLocalID) {
        this.itemLocalID = itemLocalID;
    }

    public void setPrice(long price) {
        this.price = price;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P235_ItemPriceQuote[");
        sb.append("itemLocalID=").append(this.itemLocalID).append(",price=").append(this.price).append("]");
        return sb.toString();
    }

}
