
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P249_CinematicDataEnd
    extends GWAction
{


    @Override
    public short getHeader() {
        return  249;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P249_CinematicDataEnd[");
        sb.append("]");
        return sb.toString();
    }

}
