
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P260_ManipulateMapObject
    extends GWAction
{

    private int objectID;
    private short action;
    private long frequency;

    @Override
    public short getHeader() {
        return  260;
    }

    public void setObjectID(int objectID) {
        this.objectID = objectID;
    }

    public void setAction(short action) {
        this.action = action;
    }

    public void setFrequency(long frequency) {
        this.frequency = frequency;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P260_ManipulateMapObject[");
        sb.append("objectID=").append(this.objectID).append(",action=").append(this.action).append(",frequency=").append(this.frequency).append("]");
        return sb.toString();
    }

}
