
package gwlpr.protocol.gameserver.outbound;

import java.util.Arrays;
import gwlpr.protocol.serialization.GWMessage;
import gwlpr.protocol.util.IsArray;


/**
 * Auto-generated by PacketCodeGen.
 * This is used to add guilds to the alliance tab of
 * the guild window. The guild must first be created
 * with P278 (or P279 for the player's guild).
 * 
 */
public final class P268_GuildAllyAdd
    extends GWMessage
{

    private int localID;
    @IsArray(constant = true, size = 16, prefixLength = -1)
    private byte[] guildHallData;
    private short type;
    private long joinDate;

    @Override
    public short getHeader() {
        return  268;
    }

    public void setLocalID(int localID) {
        this.localID = localID;
    }

    public void setGuildHallData(byte[] guildHallData) {
        this.guildHallData = guildHallData;
    }

    public void setType(short type) {
        this.type = type;
    }

    public void setJoinDate(long joinDate) {
        this.joinDate = joinDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P268_GuildAllyAdd[");
        sb.append("localID=").append(this.localID).append(",guildHallData=").append(Arrays.toString(this.guildHallData)).append(",type=").append(this.type).append(",joinDate=").append(this.joinDate).append("]");
        return sb.toString();
    }

}
