
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P275_GuildMemberType
    extends GWMessage
{

    private short type;

    @Override
    public short getHeader() {
        return  275;
    }

    public void setType(short type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P275_GuildMemberType[");
        sb.append("type=").append(this.type).append("]");
        return sb.toString();
    }

}
