
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P328_SwapItems
    extends GWMessage
{

    private int itemStreamID;
    private long itemLocalID1;
    private long itemLocalID2;

    @Override
    public short getHeader() {
        return  328;
    }

    public void setItemStreamID(int itemStreamID) {
        this.itemStreamID = itemStreamID;
    }

    public void setItemLocalID1(long itemLocalID1) {
        this.itemLocalID1 = itemLocalID1;
    }

    public void setItemLocalID2(long itemLocalID2) {
        this.itemLocalID2 = itemLocalID2;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P328_SwapItems[");
        sb.append("itemStreamID=").append(this.itemStreamID).append(",itemLocalID1=").append(this.itemLocalID1).append(",itemLocalID2=").append(this.itemLocalID2).append("]");
        return sb.toString();
    }

}
