
package gwlpr.protocol.gameserver.outbound;

import java.util.Arrays;
import gwlpr.protocol.serialization.GWAction;
import gwlpr.protocol.util.IsArray;
import gwlpr.protocol.util.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * This Packet describes an item in general.
 * 
 */
public final class P343_ItemGeneral
    extends GWAction
{

    private long itemLocalID;
    private long fileID;
    private short itemType;
    private short unknown1;
    private int dyeColor;
    private int materials;
    private short unknown2;
    private long itemFlags;
    private long merchantPrice;
    private long itemID;
    private long quantity;
    private String name;
    @IsArray(constant = false, size = 64, prefixLength = 2)
    private P343_ItemGeneral.NestedItemStats[] itemStats;

    @Override
    public short getHeader() {
        return  343;
    }

    public void setItemLocalID(long itemLocalID) {
        this.itemLocalID = itemLocalID;
    }

    public void setFileID(long fileID) {
        this.fileID = fileID;
    }

    public void setItemType(short itemType) {
        this.itemType = itemType;
    }

    public void setUnknown1(short unknown1) {
        this.unknown1 = unknown1;
    }

    public void setDyeColor(int dyeColor) {
        this.dyeColor = dyeColor;
    }

    public void setMaterials(int materials) {
        this.materials = materials;
    }

    public void setUnknown2(short unknown2) {
        this.unknown2 = unknown2;
    }

    public void setItemFlags(long itemFlags) {
        this.itemFlags = itemFlags;
    }

    public void setMerchantPrice(long merchantPrice) {
        this.merchantPrice = merchantPrice;
    }

    public void setItemID(long itemID) {
        this.itemID = itemID;
    }

    public void setQuantity(long quantity) {
        this.quantity = quantity;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setItemStats(P343_ItemGeneral.NestedItemStats[] itemStats) {
        this.itemStats = itemStats;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P343_ItemGeneral[");
        sb.append("itemLocalID=").append(this.itemLocalID).append(",fileID=").append(this.fileID).append(",itemType=").append(this.itemType).append(",unknown1=").append(this.unknown1).append(",dyeColor=").append(this.dyeColor).append(",materials=").append(this.materials).append(",unknown2=").append(this.unknown2).append(",itemFlags=").append(this.itemFlags).append(",merchantPrice=").append(this.merchantPrice).append(",itemID=").append(this.itemID).append(",quantity=").append(this.quantity).append(",name=").append(this.name.toString()).append(",itemStats=").append(Arrays.toString(this.itemStats)).append("]");
        return sb.toString();
    }

    public final static class NestedItemStats
        implements NestedMarker
    {

        private long stat;

        public void setStat(long stat) {
            this.stat = stat;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("NestedItemStats[");
            sb.append("stat=").append(this.stat).append("]");
            return sb.toString();
        }

    }

}
