
package gwlpr.protocol.gameserver.outbound;

import java.util.Arrays;
import gwlpr.protocol.serialization.GWAction;
import gwlpr.protocol.util.IsArray;
import gwlpr.protocol.util.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P344_Unknown
    extends GWAction
{

    private long unknown1;
    private long unknown2;
    private short unknown3;
    private short unknown4;
    private int unknown5;
    private int unknown6;
    private short unknown7;
    private long unknown8;
    private long unknown9;
    private long unknown10;
    private long unknown11;
    private String unknown12;
    @IsArray(constant = false, size = 64, prefixLength = 2)
    private P344_Unknown.NestedUnknown13 [] unknown13;

    @Override
    public short getHeader() {
        return  344;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(long unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(short unknown3) {
        this.unknown3 = unknown3;
    }

    public void setUnknown4(short unknown4) {
        this.unknown4 = unknown4;
    }

    public void setUnknown5(int unknown5) {
        this.unknown5 = unknown5;
    }

    public void setUnknown6(int unknown6) {
        this.unknown6 = unknown6;
    }

    public void setUnknown7(short unknown7) {
        this.unknown7 = unknown7;
    }

    public void setUnknown8(long unknown8) {
        this.unknown8 = unknown8;
    }

    public void setUnknown9(long unknown9) {
        this.unknown9 = unknown9;
    }

    public void setUnknown10(long unknown10) {
        this.unknown10 = unknown10;
    }

    public void setUnknown11(long unknown11) {
        this.unknown11 = unknown11;
    }

    public void setUnknown12(String unknown12) {
        this.unknown12 = unknown12;
    }

    public void setUnknown13(P344_Unknown.NestedUnknown13 [] unknown13) {
        this.unknown13 = unknown13;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P344_Unknown[");
        sb.append("unknown1=").append(this.unknown1).append(",unknown2=").append(this.unknown2).append(",unknown3=").append(this.unknown3).append(",unknown4=").append(this.unknown4).append(",unknown5=").append(this.unknown5).append(",unknown6=").append(this.unknown6).append(",unknown7=").append(this.unknown7).append(",unknown8=").append(this.unknown8).append(",unknown9=").append(this.unknown9).append(",unknown10=").append(this.unknown10).append(",unknown11=").append(this.unknown11).append(",unknown12=").append(this.unknown12 .toString()).append(",unknown13=").append(Arrays.toString(this.unknown13)).append("]");
        return sb.toString();
    }

    public final static class NestedUnknown13
        implements NestedMarker
    {

        private long unknown1;

        public void setUnknown1(long unknown1) {
            this.unknown1 = unknown1;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("NestedUnknown13[");
            sb.append("unknown1=").append(this.unknown1).append("]");
            return sb.toString();
        }

    }

}
