
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P354_Unknown
    extends GWAction
{


    @Override
    public short getHeader() {
        return  354;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P354_Unknown[");
        sb.append("]");
        return sb.toString();
    }

}
