
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P358_Unknown
    extends GWMessage
{


    @Override
    public short getHeader() {
        return  358;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P358_Unknown[");
        sb.append("]");
        return sb.toString();
    }

}
