
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P359_Unknown
    extends GWAction
{

    private long unknown1;
    private short unknown2;
    private long unknown3;
    private long unknown4;
    private long unknown5;
    private long unknown6;
    private long unknown7;
    private long unknown8;
    private short unknown9;
    private short unknown10;
    private short unknown11;
    private short unknown12;
    private short unknown13;
    private int unknown14;
    private int unknown15;
    private int unknown16;
    private int unknown17;
    private int unknown18;
    private long unknown19;
    private short unknown20;
    private short unknown21;
    private long unknown22;
    private short unknown23;

    @Override
    public short getHeader() {
        return  359;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(short unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(long unknown3) {
        this.unknown3 = unknown3;
    }

    public void setUnknown4(long unknown4) {
        this.unknown4 = unknown4;
    }

    public void setUnknown5(long unknown5) {
        this.unknown5 = unknown5;
    }

    public void setUnknown6(long unknown6) {
        this.unknown6 = unknown6;
    }

    public void setUnknown7(long unknown7) {
        this.unknown7 = unknown7;
    }

    public void setUnknown8(long unknown8) {
        this.unknown8 = unknown8;
    }

    public void setUnknown9(short unknown9) {
        this.unknown9 = unknown9;
    }

    public void setUnknown10(short unknown10) {
        this.unknown10 = unknown10;
    }

    public void setUnknown11(short unknown11) {
        this.unknown11 = unknown11;
    }

    public void setUnknown12(short unknown12) {
        this.unknown12 = unknown12;
    }

    public void setUnknown13(short unknown13) {
        this.unknown13 = unknown13;
    }

    public void setUnknown14(int unknown14) {
        this.unknown14 = unknown14;
    }

    public void setUnknown15(int unknown15) {
        this.unknown15 = unknown15;
    }

    public void setUnknown16(int unknown16) {
        this.unknown16 = unknown16;
    }

    public void setUnknown17(int unknown17) {
        this.unknown17 = unknown17;
    }

    public void setUnknown18(int unknown18) {
        this.unknown18 = unknown18;
    }

    public void setUnknown19(long unknown19) {
        this.unknown19 = unknown19;
    }

    public void setUnknown20(short unknown20) {
        this.unknown20 = unknown20;
    }

    public void setUnknown21(short unknown21) {
        this.unknown21 = unknown21;
    }

    public void setUnknown22(long unknown22) {
        this.unknown22 = unknown22;
    }

    public void setUnknown23(short unknown23) {
        this.unknown23 = unknown23;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P359_Unknown[");
        sb.append("unknown1=").append(this.unknown1).append(",unknown2=").append(this.unknown2).append(",unknown3=").append(this.unknown3).append(",unknown4=").append(this.unknown4).append(",unknown5=").append(this.unknown5).append(",unknown6=").append(this.unknown6).append(",unknown7=").append(this.unknown7).append(",unknown8=").append(this.unknown8).append(",unknown9=").append(this.unknown9).append(",unknown10=").append(this.unknown10).append(",unknown11=").append(this.unknown11).append(",unknown12=").append(this.unknown12).append(",unknown13=").append(this.unknown13).append(",unknown14=").append(this.unknown14).append(",unknown15=").append(this.unknown15).append(",unknown16=").append(this.unknown16).append(",unknown17=").append(this.unknown17).append(",unknown18=").append(this.unknown18).append(",unknown19=").append(this.unknown19).append(",unknown20=").append(this.unknown20).append(",unknown21=").append(this.unknown21).append(",unknown22=").append(this.unknown22).append(",unknown23=").append(this.unknown23).append("]");
        return sb.toString();
    }

}
