
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * First packet after handshake if its not an
 * instance load process. Initiates the char create
 * process.
 * 
 */
public final class P379_CharacterCreateHead
    extends GWMessage
{


    @Override
    public short getHeader() {
        return  379;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P379_CharacterCreateHead[");
        sb.append("]");
        return sb.toString();
    }

}
