
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P384_Unknown
    extends GWMessage
{


    @Override
    public short getHeader() {
        return  384;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P384_Unknown[");
        sb.append("]");
        return sb.toString();
    }

}
