
package gwlpr.protocol.gameserver.outbound;

import java.util.Arrays;
import gwlpr.protocol.serialization.GWAction;
import gwlpr.protocol.util.IsArray;
import gwlpr.protocol.util.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P398_Unknown
    extends GWAction
{

    private long unknown1;
    private int unknown2;
    private int unknown3;
    private short unknown4;
    private short unknown5;
    private short unknown6;
    @IsArray(constant = false, size = 2, prefixLength = 2)
    private P398_Unknown.NestedUnknown7 [] unknown7;

    @Override
    public short getHeader() {
        return  398;
    }

    public void setUnknown1(long unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(int unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(int unknown3) {
        this.unknown3 = unknown3;
    }

    public void setUnknown4(short unknown4) {
        this.unknown4 = unknown4;
    }

    public void setUnknown5(short unknown5) {
        this.unknown5 = unknown5;
    }

    public void setUnknown6(short unknown6) {
        this.unknown6 = unknown6;
    }

    public void setUnknown7(P398_Unknown.NestedUnknown7 [] unknown7) {
        this.unknown7 = unknown7;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P398_Unknown[");
        sb.append("unknown1=").append(this.unknown1).append(",unknown2=").append(this.unknown2).append(",unknown3=").append(this.unknown3).append(",unknown4=").append(this.unknown4).append(",unknown5=").append(this.unknown5).append(",unknown6=").append(this.unknown6).append(",unknown7=").append(Arrays.toString(this.unknown7)).append("]");
        return sb.toString();
    }

    public final static class NestedUnknown7
        implements NestedMarker
    {

        private short unknown1;
        private short unknown2;
        private short unknown3;
        private short unknown4;
        private short unknown5;
        private short unknown6;
        private short unknown7;
        private int unknown8;
        private short unknown9;
        private String unknown10;

        public void setUnknown1(short unknown1) {
            this.unknown1 = unknown1;
        }

        public void setUnknown2(short unknown2) {
            this.unknown2 = unknown2;
        }

        public void setUnknown3(short unknown3) {
            this.unknown3 = unknown3;
        }

        public void setUnknown4(short unknown4) {
            this.unknown4 = unknown4;
        }

        public void setUnknown5(short unknown5) {
            this.unknown5 = unknown5;
        }

        public void setUnknown6(short unknown6) {
            this.unknown6 = unknown6;
        }

        public void setUnknown7(short unknown7) {
            this.unknown7 = unknown7;
        }

        public void setUnknown8(int unknown8) {
            this.unknown8 = unknown8;
        }

        public void setUnknown9(short unknown9) {
            this.unknown9 = unknown9;
        }

        public void setUnknown10(String unknown10) {
            this.unknown10 = unknown10;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("NestedUnknown7[");
            sb.append("unknown1=").append(this.unknown1).append(",unknown2=").append(this.unknown2).append(",unknown3=").append(this.unknown3).append(",unknown4=").append(this.unknown4).append(",unknown5=").append(this.unknown5).append(",unknown6=").append(this.unknown6).append(",unknown7=").append(this.unknown7).append(",unknown8=").append(this.unknown8).append(",unknown9=").append(this.unknown9).append(",unknown10=").append(this.unknown10 .toString()).append("]");
            return sb.toString();
        }

    }

}
