
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P407_Unknown
    extends GWMessage
{

    private short unknown1;
    private short unknown2;
    private long unknown3;
    private String unknown4;
    private long unknown5;
    private String unknown6;
    private long unknown7;
    private short unknown8;
    private short unknown9;

    @Override
    public short getHeader() {
        return  407;
    }

    public void setUnknown1(short unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(short unknown2) {
        this.unknown2 = unknown2;
    }

    public void setUnknown3(long unknown3) {
        this.unknown3 = unknown3;
    }

    public void setUnknown4(String unknown4) {
        this.unknown4 = unknown4;
    }

    public void setUnknown5(long unknown5) {
        this.unknown5 = unknown5;
    }

    public void setUnknown6(String unknown6) {
        this.unknown6 = unknown6;
    }

    public void setUnknown7(long unknown7) {
        this.unknown7 = unknown7;
    }

    public void setUnknown8(short unknown8) {
        this.unknown8 = unknown8;
    }

    public void setUnknown9(short unknown9) {
        this.unknown9 = unknown9;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P407_Unknown[");
        sb.append("unknown1=").append(this.unknown1).append(",unknown2=").append(this.unknown2).append(",unknown3=").append(this.unknown3).append(",unknown4=").append(this.unknown4 .toString()).append(",unknown5=").append(this.unknown5).append(",unknown6=").append(this.unknown6 .toString()).append(",unknown7=").append(this.unknown7).append(",unknown8=").append(this.unknown8).append(",unknown9=").append(this.unknown9).append("]");
        return sb.toString();
    }

}
