
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P423_Unknown
    extends GWMessage
{


    @Override
    public short getHeader() {
        return  423;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P423_Unknown[");
        sb.append("]");
        return sb.toString();
    }

}
