
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P450_PartyMemberReady
    extends GWAction
{

    private int partyId;
    private int charLocalID;
    private short isReady;

    @Override
    public short getHeader() {
        return  450;
    }

    public void setPartyId(int partyId) {
        this.partyId = partyId;
    }

    public void setCharLocalID(int charLocalID) {
        this.charLocalID = charLocalID;
    }

    public void setIsReady(short isReady) {
        this.isReady = isReady;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P450_PartyMemberReady[");
        sb.append("partyId=").append(this.partyId).append(",charLocalID=").append(this.charLocalID).append(",isReady=").append(this.isReady).append("]");
        return sb.toString();
    }

}
