
package gwlpr.protocol.gameserver.outbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P452_PartyMembersEnd
    extends GWAction
{

    private int partyId;

    @Override
    public short getHeader() {
        return  452;
    }

    public void setPartyId(int partyId) {
        this.partyId = partyId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P452_PartyMembersEnd[");
        sb.append("partyId=").append(this.partyId).append("]");
        return sb.toString();
    }

}
