
package gwlpr.protocol.gameserver.outbound;

import java.util.Arrays;
import gwlpr.protocol.serialization.GWMessage;
import gwlpr.protocol.util.IsArray;
import gwlpr.protocol.util.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P456_Unknown
    extends GWMessage
{

    @IsArray(constant = false, size = 16, prefixLength = 2)
    private P456_Unknown.NestedUnknown1 [] unknown1;
    @IsArray(constant = false, size = 16, prefixLength = 2)
    private P456_Unknown.NestedUnknown2 [] unknown2;

    @Override
    public short getHeader() {
        return  456;
    }

    public void setUnknown1(P456_Unknown.NestedUnknown1 [] unknown1) {
        this.unknown1 = unknown1;
    }

    public void setUnknown2(P456_Unknown.NestedUnknown2 [] unknown2) {
        this.unknown2 = unknown2;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P456_Unknown[");
        sb.append("unknown1=").append(Arrays.toString(this.unknown1)).append(",unknown2=").append(Arrays.toString(this.unknown2)).append("]");
        return sb.toString();
    }

    public final static class NestedUnknown1
        implements NestedMarker
    {

        private int unknown1;

        public void setUnknown1(int unknown1) {
            this.unknown1 = unknown1;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("NestedUnknown1[");
            sb.append("unknown1=").append(this.unknown1).append("]");
            return sb.toString();
        }

    }

    public final static class NestedUnknown2
        implements NestedMarker
    {

        private long unknown1;
        private long unknown2;
        private long unknown3;

        public void setUnknown1(long unknown1) {
            this.unknown1 = unknown1;
        }

        public void setUnknown2(long unknown2) {
            this.unknown2 = unknown2;
        }

        public void setUnknown3(long unknown3) {
            this.unknown3 = unknown3;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("NestedUnknown2[");
            sb.append("unknown1=").append(this.unknown1).append(",unknown2=").append(this.unknown2).append(",unknown3=").append(this.unknown3).append("]");
            return sb.toString();
        }

    }

}
