//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.13 at 01:53:40 PM CEST 
//


package com.packetcodegen.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="prefixType" type="{}PacketSimpleTypes" default="int16" />
 *       &lt;attribute name="minOccurs" type="{}Occurance" default="1" />
 *       &lt;attribute name="maxOccurs" type="{}Occurance" default="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayInfo")
@XmlSeeAlso({
    PacketNestedType.class,
    PacketFieldType.class
})
public class ArrayInfo {

    @XmlAttribute(name = "prefixType")
    protected PacketSimpleTypes prefixType;
    @XmlAttribute(name = "minOccurs")
    protected String minOccurs;
    @XmlAttribute(name = "maxOccurs")
    protected String maxOccurs;

    /**
     * Gets the value of the prefixType property.
     * 
     * @return
     *     possible object is
     *     {@link PacketSimpleTypes }
     *     
     */
    public PacketSimpleTypes getPrefixType() {
        if (prefixType == null) {
            return PacketSimpleTypes.INT_16;
        } else {
            return prefixType;
        }
    }

    /**
     * Sets the value of the prefixType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PacketSimpleTypes }
     *     
     */
    public void setPrefixType(PacketSimpleTypes value) {
        this.prefixType = value;
    }

    /**
     * Gets the value of the minOccurs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinOccurs() {
        if (minOccurs == null) {
            return "1";
        } else {
            return minOccurs;
        }
    }

    /**
     * Sets the value of the minOccurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinOccurs(String value) {
        this.minOccurs = value;
    }

    /**
     * Gets the value of the maxOccurs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxOccurs() {
        if (maxOccurs == null) {
            return "1";
        } else {
            return maxOccurs;
        }
    }

    /**
     * Sets the value of the maxOccurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxOccurs(String value) {
        this.maxOccurs = value;
    }

}
