
package gwlpr.protocol.gameserver.inbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P004_Unknown
    extends GWAction
{


    @Override
    public short getHeader() {
        return  4;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P004_Unknown[");
        sb.append("]");
        return sb.toString();
    }

}
