
package gwlpr.protocol.gameserver.inbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P014_Unknown
    extends GWMessage
{

    private long agentID1;
    private long agentID2;

    @Override
    public short getHeader() {
        return  14;
    }

    public long getAgentID1() {
        return agentID1;
    }

    public long getAgentID2() {
        return agentID2;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P014_Unknown[");
        sb.append("agentID1=").append(this.agentID1).append(",agentID2=").append(this.agentID2).append("]");
        return sb.toString();
    }

}
