
package gwlpr.protocol.gameserver.inbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P020_Unknown
    extends GWAction
{

    private long agentID1;
    private long unknown2;
    private long unknown3;
    private long agentID4;

    @Override
    public short getHeader() {
        return  20;
    }

    public long getAgentID1() {
        return agentID1;
    }

    public long getUnknown2() {
        return unknown2;
    }

    public long getUnknown3() {
        return unknown3;
    }

    public long getAgentID4() {
        return agentID4;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P020_Unknown[");
        sb.append("agentID1=").append(this.agentID1).append(",unknown2=").append(this.unknown2).append(",unknown3=").append(this.unknown3).append(",agentID4=").append(this.agentID4).append("]");
        return sb.toString();
    }

}
