
package gwlpr.protocol.gameserver.inbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P049_Unknown
    extends GWAction
{

    private long unknown1;
    private short unknown2;
    private short unknown3;
    private short unknown4;
    private short unknown5;
    private short unknown6;
    private int unknown7;
    private short unknown8;

    @Override
    public short getHeader() {
        return  49;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public short getUnknown2() {
        return unknown2;
    }

    public short getUnknown3() {
        return unknown3;
    }

    public short getUnknown4() {
        return unknown4;
    }

    public short getUnknown5() {
        return unknown5;
    }

    public short getUnknown6() {
        return unknown6;
    }

    public int getUnknown7() {
        return unknown7;
    }

    public short getUnknown8() {
        return unknown8;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P049_Unknown[");
        sb.append("unknown1=").append(this.unknown1).append(",unknown2=").append(this.unknown2).append(",unknown3=").append(this.unknown3).append(",unknown4=").append(this.unknown4).append(",unknown5=").append(this.unknown5).append(",unknown6=").append(this.unknown6).append(",unknown7=").append(this.unknown7).append(",unknown8=").append(this.unknown8).append("]");
        return sb.toString();
    }

}
