
package gwlpr.protocol.gameserver.inbound;

import gwlpr.protocol.serialization.GWMessage;
import gwlpr.protocol.util.Vector2;


/**
 * Auto-generated by PacketCodeGen.
 * This packet requires us to find a path to the
 * position and guide the char there.
 * 
 */
public final class P055_GotoPostion
    extends GWMessage
{

    private Vector2 positionVector;
    private long positionPlane;

    @Override
    public short getHeader() {
        return  55;
    }

    public Vector2 getPositionVector() {
        return positionVector;
    }

    public long getPositionPlane() {
        return positionPlane;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P055_GotoPostion[");
        sb.append("positionVector=").append(this.positionVector.toString()).append(",positionPlane=").append(this.positionPlane).append("]");
        return sb.toString();
    }

}
