
package gwlpr.protocol.gameserver.inbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P084_ReplaceSkill
    extends GWMessage
{

    private long agentID;
    private long skillSlot;
    private long skillID;
    private long unknown;

    @Override
    public short getHeader() {
        return  84;
    }

    public long getAgentID() {
        return agentID;
    }

    public long getSkillSlot() {
        return skillSlot;
    }

    public long getSkillID() {
        return skillID;
    }

    public long getUnknown() {
        return unknown;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P084_ReplaceSkill[");
        sb.append("agentID=").append(this.agentID).append(",skillSlot=").append(this.skillSlot).append(",skillID=").append(this.skillID).append(",unknown=").append(this.unknown).append("]");
        return sb.toString();
    }

}
