
package gwlpr.protocol.gameserver.inbound;

import java.util.Arrays;
import gwlpr.protocol.serialization.GWMessage;
import gwlpr.protocol.util.IsArray;
import gwlpr.protocol.util.NestedMarker;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P085_Unknown
    extends GWMessage
{

    private long agentID1;
    @IsArray(constant = false, size = 8, prefixLength = 2)
    private P085_Unknown.NestedUnknown2 [] unknown2;

    @Override
    public short getHeader() {
        return  85;
    }

    public long getAgentID1() {
        return agentID1;
    }

    public P085_Unknown.NestedUnknown2 [] getUnknown2() {
        return unknown2;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P085_Unknown[");
        sb.append("agentID1=").append(this.agentID1).append(",unknown2=").append(Arrays.toString(this.unknown2)).append("]");
        return sb.toString();
    }

    public final static class NestedUnknown2
        implements NestedMarker
    {

        private long unknown1;

        public long getUnknown1() {
            return unknown1;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("NestedUnknown2[");
            sb.append("unknown1=").append(this.unknown1).append("]");
            return sb.toString();
        }

    }

}
