
package gwlpr.protocol.gameserver.inbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P091_Unknown
    extends GWMessage
{


    @Override
    public short getHeader() {
        return  91;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P091_Unknown[");
        sb.append("]");
        return sb.toString();
    }

}
