
package gwlpr.protocol.gameserver.inbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P156_Unknown
    extends GWMessage
{


    @Override
    public short getHeader() {
        return  156;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P156_Unknown[");
        sb.append("]");
        return sb.toString();
    }

}
