
package gwlpr.protocol.gameserver.inbound;

import gwlpr.protocol.serialization.GWAction;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P178_Unknown
    extends GWAction
{


    @Override
    public short getHeader() {
        return  178;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P178_Unknown[");
        sb.append("]");
        return sb.toString();
    }

}
