
package gwlpr.protocol.gameserver.inbound;

import gwlpr.protocol.serialization.GWMessage;


/**
 * Auto-generated by PacketCodeGen.
 * 
 */
public final class P186_Unknown
    extends GWMessage
{

    private long unknown1;
    private int unknown2;

    @Override
    public short getHeader() {
        return  186;
    }

    public long getUnknown1() {
        return unknown1;
    }

    public int getUnknown2() {
        return unknown2;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("P186_Unknown[");
        sb.append("unknown1=").append(this.unknown1).append(",unknown2=").append(this.unknown2).append("]");
        return sb.toString();
    }

}
